/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing AccountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class AccountRequestTests : IDisposable
    {
        private AccountRequest instance;

        public AccountRequestTests()
        {
            instance = new AccountRequest(
                alias: (string)TestHelpers.getTestValue(typeof(string)),
                label: (string)TestHelpers.getTestValue(typeof(string))
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountRequest
        /// </summary>
        [Fact]
        public void AccountRequestInstanceTest()
        {
            Assert.IsType<AccountRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            instance.Alias = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Alias);
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            instance.Label = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Label);
        }

        /// <summary>
        /// Test serialize a AccountRequest to JSON string - all values are present
        /// </summary>
        [Fact]
        public void AccountRequestSerializeToJSONTest()
        {
            string json = instance.ToJson();
            //Console.WriteLine("++AccountRequest++" );
            //Console.WriteLine(json);

            //Console.WriteLine("does it contain - alias ++ " + json.Contains("alias"));
            Assert.Contains("alias", json);

            //Console.WriteLine("does it contain - label ++ " + json.Contains("label"));
            Assert.Contains("label", json);
        }

        /// <summary>
        /// Test serialize a AccountRequest to JSON string - null values are stripped
        /// </summary>
        [Fact]
        public void AccountRequestSerializeToJSONStripNullTest()
        {
            string json = instance.ToJson();
            Assert.DoesNotContain("null", json);
        }
    }
}
