/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing CallControlWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class CallControlWebhookTests : IDisposable
    {
        private CallControlWebhook instance;

        public CallControlWebhookTests()
        {
            instance = new CallControlWebhook(
                requestType: (string)TestHelpers.getTestValue(typeof(string)),
                callId: (string)TestHelpers.getTestValue(typeof(string)),
                accountId: (string)TestHelpers.getTestValue(typeof(string)),
                conferenceId: (string)TestHelpers.getTestValue(typeof(string)),
                digits: (string)TestHelpers.getTestValue(typeof(string))
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CallControlWebhook
        /// </summary>
        [Fact]
        public void CallControlWebhookInstanceTest()
        {
            Assert.IsType<CallControlWebhook>(instance);
        }

        /// <summary>
        /// Test the property 'RequestType'
        /// </summary>
        [Fact]
        public void RequestTypeTest() { }

        /// <summary>
        /// Test the property 'CallId'
        /// </summary>
        [Fact]
        public void CallIdTest()
        {
            instance.CallId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CallId);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            instance.AccountId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.AccountId);
        }

        /// <summary>
        /// Test the property 'ConferenceId'
        /// </summary>
        [Fact]
        public void ConferenceIdTest()
        {
            instance.ConferenceId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ConferenceId);
        }

        /// <summary>
        /// Test the property 'Digits'
        /// </summary>
        [Fact]
        public void DigitsTest()
        {
            instance.Digits = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Digits);
        }

        [Fact]
        public void TestDeserializeJsonToCallControlWebhook()
        {
            string payload = @"{ ""requestType"": ""callControl"" }";
            CallControlWebhook deserialized = CallControlWebhook.Deserialize(payload);
            Assert.IsType<CallControlWebhook>(deserialized);
            Assert.Equal("callControl", deserialized.RequestType);
        }

        /// <summary>
        /// Test serialize a CallControlWebhook to JSON string - all values are present
        /// </summary>
        [Fact]
        public void CallControlWebhookSerializeToJSONTest()
        {
            string json = instance.ToJson();

            Assert.Contains("requestType", json);

            Assert.Contains("callId", json);

            Assert.Contains("accountId", json);

            Assert.Contains("conferenceId", json);

            Assert.Contains("digits", json);
        }

        /// <summary>
        /// Test serialize a CallControlWebhook to JSON string - null values are stripped
        /// </summary>
        [Fact]
        public void CallControlWebhookSerializeToJSONStripNullTest()
        {
            string json = instance.ToJson();
            Assert.DoesNotContain("null", json);
        }
    }
}
