/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */




using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using freeclimb.Api;
using freeclimb.Model;
using freeclimb.Client;
using System.Reflection;
using Newtonsoft.Json;


namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing ConferenceResultAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConferenceResultAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConferenceResultAllOf
        private ConferenceResultAllOf instance;

        public ConferenceResultAllOfTests()
        {
            instance = new ConferenceResultAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConferenceResultAllOf
        /// </summary>
        [Fact]
        public void ConferenceResultAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConferenceResultAllOf
            Assert.IsType<ConferenceResultAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'ConferenceId'
        /// </summary>
        [Fact]
        public void ConferenceIdTest()
        {
            instance.ConferenceId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ConferenceId);
            
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            instance.AccountId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.AccountId);
            
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            instance.Alias = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Alias);
            
        }
        /// <summary>
        /// Test the property 'PlayBeep'
        /// </summary>
        [Fact]
        public void PlayBeepTest()
        {
            //model.setPlayBeep(PlayBeep.ALWAYS);
            //Assert.assertEquals(model.getPlayBeep(),PlayBeep.ALWAYS);
            //model.setPlayBeep(PlayBeep.NEVER);
            //Assert.assertEquals(model.getPlayBeep(),PlayBeep.NEVER);
            //model.setPlayBeep(PlayBeep.ENTRY_ONLY);
            //Assert.assertEquals(model.getPlayBeep(),PlayBeep.ENTRY_ONLY);
            //model.setPlayBeep(PlayBeep.EXIT_ONLY);
            //Assert.assertEquals(model.getPlayBeep(),PlayBeep.EXIT_ONLY);
            
            //model.setPlayBeep(ConferenceResultAllOf.PlayBeep.ALWAYS);
            //Assert.assertEquals(model.getPlayBeep(),ConferenceResultAllOf.PlayBeep.ALWAYS);
            
            //model.setPlayBeep(ConferenceResultAllOf.PlayBeep.NEVER);
            //Assert.assertEquals(model.getPlayBeep(),ConferenceResultAllOf.PlayBeep.NEVER);
            
            //model.setPlayBeep(ConferenceResultAllOf.PlayBeep.ENTRY_ONLY);
            //Assert.assertEquals(model.getPlayBeep(),ConferenceResultAllOf.PlayBeep.ENTRY_ONLY);
            
            //model.setPlayBeep(ConferenceResultAllOf.PlayBeep.EXIT_ONLY);
            //Assert.assertEquals(model.getPlayBeep(),ConferenceResultAllOf.PlayBeep.EXIT_ONLY);
            
        }
        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Fact]
        public void RecordTest()
        {
            instance.Record = false;
            Assert.Equal(false, instance.Record);       
            
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            //model.setStatus(ConferenceStatus.EMPTY);
            //Assert.assertEquals(model.getStatus(),ConferenceStatus.EMPTY);
            //model.setStatus(ConferenceStatus.POPULATED);
            //Assert.assertEquals(model.getStatus(),ConferenceStatus.POPULATED);
            //model.setStatus(ConferenceStatus.IN_PROGRESS);
            //Assert.assertEquals(model.getStatus(),ConferenceStatus.IN_PROGRESS);
            //model.setStatus(ConferenceStatus.TERMINATED);
            //Assert.assertEquals(model.getStatus(),ConferenceStatus.TERMINATED);
            
            //model.setStatus(ConferenceResultAllOf.ConferenceStatus.EMPTY);
            //Assert.assertEquals(model.getStatus(),ConferenceResultAllOf.ConferenceStatus.EMPTY);
            
            //model.setStatus(ConferenceResultAllOf.ConferenceStatus.POPULATED);
            //Assert.assertEquals(model.getStatus(),ConferenceResultAllOf.ConferenceStatus.POPULATED);
            
            //model.setStatus(ConferenceResultAllOf.ConferenceStatus.IN_PROGRESS);
            //Assert.assertEquals(model.getStatus(),ConferenceResultAllOf.ConferenceStatus.IN_PROGRESS);
            
            //model.setStatus(ConferenceResultAllOf.ConferenceStatus.TERMINATED);
            //Assert.assertEquals(model.getStatus(),ConferenceResultAllOf.ConferenceStatus.TERMINATED);
            
        }
        /// <summary>
        /// Test the property 'WaitUrl'
        /// </summary>
        [Fact]
        public void WaitUrlTest()
        {
            instance.WaitUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.WaitUrl);
            
        }
        /// <summary>
        /// Test the property 'ActionUrl'
        /// </summary>
        [Fact]
        public void ActionUrlTest()
        {
            instance.ActionUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ActionUrl);
            
        }
        /// <summary>
        /// Test the property 'StatusCallbackUrl'
        /// </summary>
        [Fact]
        public void StatusCallbackUrlTest()
        {
            instance.StatusCallbackUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.StatusCallbackUrl);
            
        }
        /// <summary>
        /// Test the property 'SubresourceUris'
        /// </summary>
        [Fact]
        public void SubresourceUrisTest()
        {
            object testObject = new object();
            instance.SubresourceUris = testObject;
            Assert.Equal(testObject, instance.SubresourceUris);
            
        }
    }
}
