/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using freeclimb.Model;
using freeclimb.Client;
using System.Reflection;
using Newtonsoft.Json;

using freeclimb.Enums;
using System.Collections;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing CreateConferenceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateConferenceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateConferenceRequest
        private CreateConferenceRequest instance;

        public CreateConferenceRequestTests()
        {
            instance = new CreateConferenceRequest(
                
                alias: (string)getTestValue(typeof(string)),
                
                playBeep: (PlayBeep)getTestValue(typeof(PlayBeep)),
                
                record: (bool)getTestValue(typeof(bool)),
                
                waitUrl: (string)getTestValue(typeof(string)),
                
                statusCallbackUrl: (string)getTestValue(typeof(string))
                
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateConferenceRequest
        /// </summary>
        [Fact]
        public void CreateConferenceRequestInstanceTest()
        {
            Assert.IsType<CreateConferenceRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            instance.Alias = "TEST_STRING";
            Assert.Equal(instance.Alias, "TEST_STRING");
            
        }

        /// <summary>
        /// Test the property 'PlayBeep'
        /// </summary>
        [Fact]
        public void PlayBeepTest()
        {
            instance.PlayBeep = PlayBeep.ALWAYS;
            Assert.Equal(instance.PlayBeep, PlayBeep.ALWAYS);
            instance.PlayBeep = PlayBeep.NEVER;
            Assert.Equal(instance.PlayBeep, PlayBeep.NEVER);
            instance.PlayBeep = PlayBeep.ENTRY_ONLY;
            Assert.Equal(instance.PlayBeep, PlayBeep.ENTRY_ONLY);
            instance.PlayBeep = PlayBeep.EXIT_ONLY;
            Assert.Equal(instance.PlayBeep, PlayBeep.EXIT_ONLY);
            
        }

        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Fact]
        public void RecordTest()
        {
            instance.Record = false;
            Assert.Equal(instance.Record, false);
            
        }

        /// <summary>
        /// Test the property 'WaitUrl'
        /// </summary>
        [Fact]
        public void WaitUrlTest()
        {
            instance.WaitUrl = "TEST_STRING";
            Assert.Equal(instance.WaitUrl, "TEST_STRING");
            
        }

        /// <summary>
        /// Test the property 'StatusCallbackUrl'
        /// </summary>
        [Fact]
        public void StatusCallbackUrlTest()
        {
            instance.StatusCallbackUrl = "TEST_STRING";
            Assert.Equal(instance.StatusCallbackUrl, "TEST_STRING");
            
        }

        public object getTestValue(Type type)
        {
            if (type == typeof(int) || type == typeof(Nullable<int>)) {
                return 1;
            }
            if (type == typeof(string) || type == typeof(Nullable<string>)) {
                return "TEST_STRING";
            }
            if (type == typeof(bool) || type == typeof(Nullable<bool>)) {
                return true;
            }
            if (type == typeof(CallStatus)) {
                return CallStatusValueConverter.FromString("completed");
            }
            if (type == typeof(CallDirection)) {
                return CallDirectionValueConverter.FromString("inbound");
            }
            if (type == typeof(GetDigitsReason)) {
                return GetDigitsReasonValueConverter.FromString("timeout");
            }
            if (type == typeof(LogLevel)) {
                return LogLevelValueConverter.FromString("info");
            }
            if (type == typeof(CallEndedReason)) {
                return CallEndedReasonValueConverter.FromString("busy");
            }
            if (type == typeof(SMSTenDLCBrandEntityType)) {
                return SMSTenDLCBrandEntityTypeValueConverter.FromString("PUBLIC_PROFIT");
            }
            if (type == typeof(SMSTenDLCBrandStockExchange)) {
                return SMSTenDLCBrandStockExchangeValueConverter.FromString("NONE");
            }
            if (type == typeof(SMSTenDLCBrandRelationship)) {
                return SMSTenDLCBrandRelationshipValueConverter.FromString("BASIC_ACCOUNT");
            }
            if (type == typeof(SMSTenDLCBrandAltBusinessIdType)) {
                return SMSTenDLCBrandAltBusinessIdTypeValueConverter.FromString("NONE");
            }
            if (type == typeof(SMSTenDLCBrandIdentityStatus)) {
                return SMSTenDLCBrandIdentityStatusValueConverter.FromString("SELF_DECLARED");
            }
            if (type == typeof(PlayBeep)) {
                return PlayBeepValueConverter.FromString("always");
            }
            if (type == typeof(UpdateCallRequestStatus)) {
                return UpdateCallRequestStatusValueConverter.FromString("canceled");
            }
            if (type == typeof(QueueResultStatus)) {
                return QueueResultStatusValueConverter.FromString("queueFull");
            }
            if (type == typeof(ConferenceStatus)) {
                return ConferenceStatusValueConverter.FromString("empty");
            }
            if (type == typeof(MachineType)) {
                return MachineTypeValueConverter.FromString("answering machine");
            }
            if (type == typeof(SMSTenDLCCampaignStatus)) {
                return SMSTenDLCCampaignStatusValueConverter.FromString("ACTIVE");
            }
            if (type == typeof(SMSTollFreeCampaignRegistrationStatus)) {
                return SMSTollFreeCampaignRegistrationStatusValueConverter.FromString("UNREGISTERED");
            }
            if (type == typeof(MessageStatus)) {
                return MessageStatusValueConverter.FromString("new");
            }
            if (type == typeof(RecordUtteranceTermReason)) {
                return RecordUtteranceTermReasonValueConverter.FromString("FINISH_KEY");
            }
            if (type == typeof(GrammarType)) {
                return GrammarTypeValueConverter.FromString("URL");
            }
            if (type == typeof(CompletionResultStatus)) {
                return CompletionResultStatusValueConverter.FromString("success");
            }
            if (type == typeof(AnsweredBy)) {
                return AnsweredByValueConverter.FromString("HUMAN");
            }
            if (type == typeof(IfMachine)) {
                return IfMachineValueConverter.FromString("redirect");
            }
            if (type == typeof(AccountType)) {
                return AccountTypeValueConverter.FromString("trial");
            }
            if (type == typeof(AccountStatus)) {
                return AccountStatusValueConverter.FromString("closed");
            }
            if (type == typeof(List<string>)) {
                return new List<string>();
            }
            if (type == typeof(List<ApplicationResult>)) {
                return new List<ApplicationResult>();
            }
            if (type == typeof(List<IncomingNumberResult>)) {
                return new List<IncomingNumberResult>();
            }
            if (type == typeof(List<SMSTollFreeCampaign>)) {
                return new List<SMSTollFreeCampaign>();
            }
            if (type == typeof(List<QueueResult>)) {
                return new List<QueueResult>();
            }
            if (type == typeof(List<AvailableNumber>)) {
                return new List<AvailableNumber>();
            }
            if (type == typeof(List<SMSTenDLCPartnerCampaign>)) {
                return new List<SMSTenDLCPartnerCampaign>();
            }
            if (type == typeof(List<PerclCommand>)) {
                return new List<PerclCommand>();
            }
            if (type == typeof(List<QueueMember>)) {
                return new List<QueueMember>();
            }
            if (type == typeof(List<QueueResult>)) {
                return new List<QueueResult>();
            }
            if (type == typeof(List<CallResult>)) {
                return new List<CallResult>();
            }
            if (type == typeof(List<ConferenceParticipantResult>)) {
                return new List<ConferenceParticipantResult>();
            }
            if (type == typeof(Capabilities)) {
                return new Capabilities();
            }
            if (type == typeof(TFN)) {
                return new TFN(campaignId="TEST_CAMPAIGN");
            }
            if (type == typeof(Dictionary<string, Object>)) {
                return new Dictionary<string, Object>();
            }
            if (type == typeof(TranscribeUtteranceRecord)) {
                return new TranscribeUtteranceRecord();
            }
            if (type == typeof(DateTime)) {
                return DateTime.Today;
            }
            if (type == typeof(DateOnly)) {
                return DateOnly.FromDateTime(DateTime.Now); 
            }
            if (type == typeof(Object)) {
                return new Dictionary<string, string>();
            }
            throw new ArgumentException("Provided type has no test value");
        }
    }
}
