/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing CreateConference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class CreateConferenceTests : IDisposable
    {
        private CreateConference instance;

        public CreateConferenceTests()
        {
            instance = new CreateConference(
                actionUrl: (string)TestHelpers.getTestValue(typeof(string)),
                alias: (string)TestHelpers.getTestValue(typeof(string)),
                playBeep: (PlayBeep)TestHelpers.getTestValue(typeof(PlayBeep)),
                record: (bool)TestHelpers.getTestValue(typeof(bool)),
                statusCallbackUrl: (string)TestHelpers.getTestValue(typeof(string)),
                waitUrl: (string)TestHelpers.getTestValue(typeof(string)),
                parentCallId: (string)TestHelpers.getTestValue(typeof(string))
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateConference
        /// </summary>
        [Fact]
        public void CreateConferenceInstanceTest()
        {
            Assert.IsType<CreateConference>(instance);
        }

        /// <summary>
        /// Test the property 'ActionUrl'
        /// </summary>
        [Fact]
        public void ActionUrlTest()
        {
            instance.ActionUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ActionUrl);
        }

        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            instance.Alias = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Alias);
        }

        /// <summary>
        /// Test the property 'PlayBeep'
        /// </summary>
        [Fact]
        public void PlayBeepTest()
        {
            instance.PlayBeep = PlayBeep.ALWAYS;
            Assert.Equal(PlayBeep.ALWAYS, instance.PlayBeep);
            instance.PlayBeep = PlayBeep.NEVER;
            Assert.Equal(PlayBeep.NEVER, instance.PlayBeep);
            instance.PlayBeep = PlayBeep.ENTRY_ONLY;
            Assert.Equal(PlayBeep.ENTRY_ONLY, instance.PlayBeep);
            instance.PlayBeep = PlayBeep.EXIT_ONLY;
            Assert.Equal(PlayBeep.EXIT_ONLY, instance.PlayBeep);
        }

        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Fact]
        public void RecordTest()
        {
            instance.Record = false;
            Assert.False(instance.Record);
        }

        /// <summary>
        /// Test the property 'StatusCallbackUrl'
        /// </summary>
        [Fact]
        public void StatusCallbackUrlTest()
        {
            instance.StatusCallbackUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.StatusCallbackUrl);
        }

        /// <summary>
        /// Test the property 'WaitUrl'
        /// </summary>
        [Fact]
        public void WaitUrlTest()
        {
            instance.WaitUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.WaitUrl);
        }

        /// <summary>
        /// Test the property 'ParentCallId'
        /// </summary>
        [Fact]
        public void ParentCallIdTest()
        {
            instance.ParentCallId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ParentCallId);
        }

        /// <summary>
        /// Test serialize a CreateConference to JSON string - all values are present
        /// </summary>
        [Fact]
        public void CreateConferenceSerializeToJSONTest()
        {
            string json = instance.ToJson();

            Assert.Contains("actionUrl", json);

            Assert.Contains("alias", json);

            Assert.Contains("playBeep", json);

            Assert.Contains("record", json);

            Assert.Contains("statusCallbackUrl", json);

            Assert.Contains("waitUrl", json);

            Assert.Contains("parentCallId", json);
        }

        /// <summary>
        /// Test serialize a CreateConference to JSON string - null values are stripped
        /// </summary>
        [Fact]
        public void CreateConferenceSerializeToJSONStripNullTest()
        {
            instance.PlayBeep = null;

            string json = instance.ToJson();
            Assert.DoesNotContain("null", json);
        }
    }
}
