/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing FilterLogsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class FilterLogsRequestTests : IDisposable
    {
        private FilterLogsRequest instance;

        public FilterLogsRequestTests()
        {
            instance = new FilterLogsRequest(pql: (string)TestHelpers.getTestValue(typeof(string)));
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterLogsRequest
        /// </summary>
        [Fact]
        public void FilterLogsRequestInstanceTest()
        {
            Assert.IsType<FilterLogsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Pql'
        /// </summary>
        [Fact]
        public void PqlTest()
        {
            instance.Pql = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Pql);
        }

        /// <summary>
        /// Test serialize a FilterLogsRequest to JSON string - all values are present
        /// </summary>
        [Fact]
        public void FilterLogsRequestSerializeToJSONTest()
        {
            string json = instance.ToJson();
            //Console.WriteLine("++FilterLogsRequest++" );
            //Console.WriteLine(json);

            //Console.WriteLine("does it contain - pql ++ " + json.Contains("pql"));
            Assert.Contains("pql", json);
        }

        /// <summary>
        /// Test serialize a FilterLogsRequest to JSON string - null values are stripped
        /// </summary>
        [Fact]
        public void FilterLogsRequestSerializeToJSONStripNullTest()
        {
            string json = instance.ToJson();
            Assert.DoesNotContain("null", json);
        }
    }
}
