/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using freeclimb.Model;
using freeclimb.Client;
using System.Reflection;
using Newtonsoft.Json;

using freeclimb.Enums;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing GetSpeech
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSpeechTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSpeech
        private GetSpeech instance;

        public GetSpeechTests()
        {
            instance = new GetSpeech(
                
                actionUrl: (string)getTestValue(typeof(string)),
                
                grammarType: (GrammarType)getTestValue(typeof(GrammarType)),
                
                grammarFile: (string)getTestValue(typeof(string)),
                
                grammarRule: (string)getTestValue(typeof(string)),
                
                playBeep: (bool)getTestValue(typeof(bool)),
                
                prompts: (List<PerclCommand>)getTestValue(typeof(List<PerclCommand>)),
                
                noInputTimeoutMs: (int)getTestValue(typeof(int)),
                
                recognitionTimeoutMs: (int)getTestValue(typeof(int)),
                
                confidenceThreshold: (decimal)getTestValue(typeof(decimal)),
                
                sensitivityLevel: (decimal)getTestValue(typeof(decimal)),
                
                speechCompleteTimeoutMs: (int)getTestValue(typeof(int)),
                
                speechIncompleteTimeoutMs: (int)getTestValue(typeof(int)),
                
                privacyMode: (bool)getTestValue(typeof(bool))
                
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSpeech
        /// </summary>
        [Fact]
        public void GetSpeechInstanceTest()
        {
            Assert.IsType<GetSpeech>(instance);
        }

        /// <summary>
        /// Test the property 'ActionUrl'
        /// </summary>
        [Fact]
        public void ActionUrlTest()
        {
            
            instance.ActionUrl = "TEST_STRING";
            Assert.Equal(instance.ActionUrl, "TEST_STRING");
        }

        /// <summary>
        /// Test the property 'GrammarType'
        /// </summary>
        [Fact]
        public void GrammarTypeTest()
        {
            instance.GrammarType = GrammarType.URL;
            Assert.Equal(instance.GrammarType, GrammarType.URL);
            instance.GrammarType = GrammarType.BUILT_IN;
            Assert.Equal(instance.GrammarType, GrammarType.BUILT_IN);
            
        }

        /// <summary>
        /// Test the property 'GrammarFile'
        /// </summary>
        [Fact]
        public void GrammarFileTest()
        {
            instance.GrammarFile = "TEST_STRING";
            Assert.Equal(instance.GrammarFile, "TEST_STRING");
            
        }

        /// <summary>
        /// Test the property 'GrammarRule'
        /// </summary>
        [Fact]
        public void GrammarRuleTest()
        {
            instance.GrammarRule = "TEST_STRING";
            Assert.Equal(instance.GrammarRule, "TEST_STRING");
            
        }

        /// <summary>
        /// Test the property 'PlayBeep'
        /// </summary>
        [Fact]
        public void PlayBeepTest()
        {
            instance.PlayBeep = false;
            Assert.Equal(instance.PlayBeep, false);
            
        }

        /// <summary>
        /// Test the property 'Prompts'
        /// </summary>
        [Fact]
        public void PromptsTest()
        {
            
            List<PerclCommand> testList = new List<PerclCommand>();
            instance.Prompts = testList;
            Assert.Equal(instance.Prompts, testList); 
        }

        /// <summary>
        /// Test the property 'NoInputTimeoutMs'
        /// </summary>
        [Fact]
        public void NoInputTimeoutMsTest()
        {
            
            instance.NoInputTimeoutMs = 1;
            Assert.Equal((int) instance.NoInputTimeoutMs, 1);
        }

        /// <summary>
        /// Test the property 'RecognitionTimeoutMs'
        /// </summary>
        [Fact]
        public void RecognitionTimeoutMsTest()
        {
            
            instance.RecognitionTimeoutMs = 1;
            Assert.Equal((int) instance.RecognitionTimeoutMs, 1);
        }

        /// <summary>
        /// Test the property 'ConfidenceThreshold'
        /// </summary>
        [Fact]
        public void ConfidenceThresholdTest()
        {
            instance.ConfidenceThreshold = new decimal(1.0);
            Assert.Equal(instance.ConfidenceThreshold, new decimal(1.0));
            
        }

        /// <summary>
        /// Test the property 'SensitivityLevel'
        /// </summary>
        [Fact]
        public void SensitivityLevelTest()
        {
            instance.SensitivityLevel = new decimal(1.0);
            Assert.Equal(instance.SensitivityLevel, new decimal(1.0));
            
        }

        /// <summary>
        /// Test the property 'SpeechCompleteTimeoutMs'
        /// </summary>
        [Fact]
        public void SpeechCompleteTimeoutMsTest()
        {
            
            instance.SpeechCompleteTimeoutMs = 1;
            Assert.Equal((int) instance.SpeechCompleteTimeoutMs, 1);
        }

        /// <summary>
        /// Test the property 'SpeechIncompleteTimeoutMs'
        /// </summary>
        [Fact]
        public void SpeechIncompleteTimeoutMsTest()
        {
            
            instance.SpeechIncompleteTimeoutMs = 1;
            Assert.Equal((int) instance.SpeechIncompleteTimeoutMs, 1);
        }

        /// <summary>
        /// Test the property 'PrivacyMode'
        /// </summary>
        [Fact]
        public void PrivacyModeTest()
        {
            instance.PrivacyMode = false;
            Assert.Equal(instance.PrivacyMode, false);
            
        }

        public object getTestValue(Type type)
        {
            if (type == typeof(int)) {
                return 1;
            }
            if (type == typeof(string)) {
                return "TEST_STRING";
            }
            throw new ArgumentException("Provided type has no test value", nameof(type));
        }
    }
}
