/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing GetSpeechWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class GetSpeechWebhookTests : IDisposable
    {
        private GetSpeechWebhook instance;

        public GetSpeechWebhookTests()
        {
            instance = new GetSpeechWebhook(
                requestType: (string)TestHelpers.getTestValue(typeof(string)),
                callId: (string)TestHelpers.getTestValue(typeof(string)),
                accountId: (string)TestHelpers.getTestValue(typeof(string)),
                from: (string)TestHelpers.getTestValue(typeof(string)),
                to: (string)TestHelpers.getTestValue(typeof(string)),
                callStatus: (CallStatus)TestHelpers.getTestValue(typeof(CallStatus)),
                direction: (CallDirection)TestHelpers.getTestValue(typeof(CallDirection)),
                conferenceId: (string)TestHelpers.getTestValue(typeof(string)),
                queueId: (string)TestHelpers.getTestValue(typeof(string)),
                reason: (GetSpeechReason)TestHelpers.getTestValue(typeof(GetSpeechReason)),
                recognitionResult: (string)TestHelpers.getTestValue(typeof(string)),
                confidence: (int)TestHelpers.getTestValue(typeof(int)),
                parentCallId: (string)TestHelpers.getTestValue(typeof(string)),
                completionReason: (string)TestHelpers.getTestValue(typeof(string)),
                completionCause: (string)TestHelpers.getTestValue(typeof(string)),
                mrcpCode: (int)TestHelpers.getTestValue(typeof(int)),
                mrcpDiagnostic: (string)TestHelpers.getTestValue(typeof(string))
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSpeechWebhook
        /// </summary>
        [Fact]
        public void GetSpeechWebhookInstanceTest()
        {
            Assert.IsType<GetSpeechWebhook>(instance);
        }

        /// <summary>
        /// Test the property 'RequestType'
        /// </summary>
        [Fact]
        public void RequestTypeTest() { }

        /// <summary>
        /// Test the property 'CallId'
        /// </summary>
        [Fact]
        public void CallIdTest()
        {
            instance.CallId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CallId);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            instance.AccountId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.AccountId);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            instance.From = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.From);
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            instance.To = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.To);
        }

        /// <summary>
        /// Test the property 'CallStatus'
        /// </summary>
        [Fact]
        public void CallStatusTest()
        {
            instance.CallStatus = CallStatus.QUEUED;
            Assert.Equal(CallStatus.QUEUED, instance.CallStatus);
            instance.CallStatus = CallStatus.RINGING;
            Assert.Equal(CallStatus.RINGING, instance.CallStatus);
            instance.CallStatus = CallStatus.IN_PROGRESS;
            Assert.Equal(CallStatus.IN_PROGRESS, instance.CallStatus);
            instance.CallStatus = CallStatus.CANCELED;
            Assert.Equal(CallStatus.CANCELED, instance.CallStatus);
            instance.CallStatus = CallStatus.COMPLETED;
            Assert.Equal(CallStatus.COMPLETED, instance.CallStatus);
            instance.CallStatus = CallStatus.FAILED;
            Assert.Equal(CallStatus.FAILED, instance.CallStatus);
            instance.CallStatus = CallStatus.BUSY;
            Assert.Equal(CallStatus.BUSY, instance.CallStatus);
            instance.CallStatus = CallStatus.NO_ANSWER;
            Assert.Equal(CallStatus.NO_ANSWER, instance.CallStatus);
        }

        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            instance.Direction = CallDirection.INBOUND;
            Assert.Equal(CallDirection.INBOUND, instance.Direction);
            instance.Direction = CallDirection.OUTBOUND_API;
            Assert.Equal(CallDirection.OUTBOUND_API, instance.Direction);
            instance.Direction = CallDirection.OUTBOUND_DIAL;
            Assert.Equal(CallDirection.OUTBOUND_DIAL, instance.Direction);
        }

        /// <summary>
        /// Test the property 'ConferenceId'
        /// </summary>
        [Fact]
        public void ConferenceIdTest()
        {
            instance.ConferenceId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ConferenceId);
        }

        /// <summary>
        /// Test the property 'QueueId'
        /// </summary>
        [Fact]
        public void QueueIdTest()
        {
            instance.QueueId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.QueueId);
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            instance.Reason = GetSpeechReason.ERROR;
            Assert.Equal(GetSpeechReason.ERROR, instance.Reason);
            instance.Reason = GetSpeechReason.HANGUP;
            Assert.Equal(GetSpeechReason.HANGUP, instance.Reason);
            instance.Reason = GetSpeechReason.DIGIT;
            Assert.Equal(GetSpeechReason.DIGIT, instance.Reason);
            instance.Reason = GetSpeechReason.NO_INPUT;
            Assert.Equal(GetSpeechReason.NO_INPUT, instance.Reason);
            instance.Reason = GetSpeechReason.NO_MATCH;
            Assert.Equal(GetSpeechReason.NO_MATCH, instance.Reason);
            instance.Reason = GetSpeechReason.RECOGNITION;
            Assert.Equal(GetSpeechReason.RECOGNITION, instance.Reason);
        }

        /// <summary>
        /// Test the property 'RecognitionResult'
        /// </summary>
        [Fact]
        public void RecognitionResultTest()
        {
            instance.RecognitionResult = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.RecognitionResult);
        }

        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Fact]
        public void ConfidenceTest()
        {
            instance.Confidence = 1;
            Assert.Equal(1, (int)instance.Confidence);
        }

        /// <summary>
        /// Test the property 'ParentCallId'
        /// </summary>
        [Fact]
        public void ParentCallIdTest()
        {
            instance.ParentCallId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ParentCallId);
        }

        /// <summary>
        /// Test the property 'CompletionReason'
        /// </summary>
        [Fact]
        public void CompletionReasonTest()
        {
            instance.CompletionReason = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CompletionReason);
        }

        /// <summary>
        /// Test the property 'CompletionCause'
        /// </summary>
        [Fact]
        public void CompletionCauseTest()
        {
            instance.CompletionCause = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CompletionCause);
        }

        /// <summary>
        /// Test the property 'MrcpCode'
        /// </summary>
        [Fact]
        public void MrcpCodeTest()
        {
            instance.MrcpCode = 1;
            Assert.Equal(1, (int)instance.MrcpCode);
        }

        /// <summary>
        /// Test the property 'MrcpDiagnostic'
        /// </summary>
        [Fact]
        public void MrcpDiagnosticTest()
        {
            instance.MrcpDiagnostic = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.MrcpDiagnostic);
        }

        [Fact]
        public void TestDeserializeJsonToGetSpeechWebhook()
        {
            string payload = @"{ ""requestType"": ""getSpeech"" }";
            GetSpeechWebhook deserialized = GetSpeechWebhook.Deserialize(payload);
            Assert.IsType<GetSpeechWebhook>(deserialized);
            Assert.Equal("getSpeech", deserialized.RequestType);
        }

        /// <summary>
        /// Test serialize a GetSpeechWebhook to JSON string - all values are present
        /// </summary>
        [Fact]
        public void GetSpeechWebhookSerializeToJSONTest()
        {
            string json = instance.ToJson();

            Assert.Contains("requestType", json);

            Assert.Contains("callId", json);

            Assert.Contains("accountId", json);

            Assert.Contains("from", json);

            Assert.Contains("to", json);

            Assert.Contains("callStatus", json);

            Assert.Contains("direction", json);

            Assert.Contains("conferenceId", json);

            Assert.Contains("queueId", json);

            Assert.Contains("reason", json);

            Assert.Contains("recognitionResult", json);

            Assert.Contains("confidence", json);

            Assert.Contains("parentCallId", json);

            Assert.Contains("completionReason", json);

            Assert.Contains("completionCause", json);

            Assert.Contains("mrcpCode", json);

            Assert.Contains("mrcpDiagnostic", json);
        }

        /// <summary>
        /// Test serialize a GetSpeechWebhook to JSON string - null values are stripped
        /// </summary>
        [Fact]
        public void GetSpeechWebhookSerializeToJSONStripNullTest()
        {
            instance.CallStatus = null;

            instance.Direction = null;

            instance.QueueId = null;

            string json = instance.ToJson();
            Assert.DoesNotContain("null", json);
        }
    }
}
