/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */




using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Text;
using freeclimb.Api;
using freeclimb.Model;
using freeclimb.Client;
using System.Reflection;
using Newtonsoft.Json;
using System.Globalization;
using freeclimb.Enums;


namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing MessageResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageResultTests
    {
        private MessageResult instance;

        public MessageResultTests()
        {
            instance = new MessageResult();
        }

        /// <summary>
        /// Test an instance of MessageResult
        /// </summary>
        [Fact]
        public void MessageResultInstanceTest()
        {
            Assert.IsType<MessageResult>(instance);
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            instance.Uri = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Uri);

        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            instance.DateCreated = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.DateCreated);

        }
        /// <summary>
        /// Test the property 'DateUpdated'
        /// </summary>
        [Fact]
        public void DateUpdatedTest()
        {
            instance.DateUpdated = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.DateUpdated);

        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Fact]
        public void RevisionTest()
        {

            instance.Revision = 1;
            Assert.Equal(1, (int)instance.Revision);
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            instance.AccountId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.AccountId);

        }
        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            instance.MessageId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.MessageId);

        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            instance.Status = MessageStatus.NEW;
            Assert.Equal(instance.Status, MessageStatus.NEW);
            instance.Status = MessageStatus.QUEUED;
            Assert.Equal(instance.Status, MessageStatus.QUEUED);
            instance.Status = MessageStatus.REJECTED;
            Assert.Equal(instance.Status, MessageStatus.REJECTED);
            instance.Status = MessageStatus.SENDING;
            Assert.Equal(instance.Status, MessageStatus.SENDING);
            instance.Status = MessageStatus.SENT;
            Assert.Equal(instance.Status, MessageStatus.SENT);
            instance.Status = MessageStatus.FAILED;
            Assert.Equal(instance.Status, MessageStatus.FAILED);
            instance.Status = MessageStatus.RECEIVED;
            Assert.Equal(instance.Status, MessageStatus.RECEIVED);
            instance.Status = MessageStatus.UNDELIVERED;
            Assert.Equal(instance.Status, MessageStatus.UNDELIVERED);
            instance.Status = MessageStatus.EXPIRED;
            Assert.Equal(instance.Status, MessageStatus.EXPIRED);
            instance.Status = MessageStatus.DELETED;
            Assert.Equal(instance.Status, MessageStatus.DELETED);
            instance.Status = MessageStatus.UNKNOWN;
            Assert.Equal(instance.Status, MessageStatus.UNKNOWN);

        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            instance.From = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.From);

        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            instance.To = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.To);

        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            instance.Text = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Text);

        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            instance.Direction = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Direction);

        }
        /// <summary>
        /// Test the property 'NotificationUrl'
        /// </summary>
        [Fact]
        public void NotificationUrlTest()
        {
            instance.NotificationUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.NotificationUrl);

        }
        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [Fact]
        public void BrandIdTest()
        {
            instance.BrandId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.BrandId);

        }
        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            instance.CampaignId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CampaignId);

        }
        /// <summary>
        /// Test the property 'SegmentCount'
        /// </summary>
        [Fact]
        public void SegmentCountTest()
        {
            instance.SegmentCount = new decimal(1.0);
            Assert.Equal(new decimal(1.0), instance.SegmentCount);

        }
        /// <summary>
        /// Test the property 'MediaUrls'
        /// </summary>
        [Fact]
        public void MediaUrlsTest()
        {
            string[] testArray = { "ElementOne", "ElementTwo", "ElementThree" };
            List<string> testList = testArray.ToList();
            instance.MediaUrls = testList;
            Assert.Equal(testList, instance.MediaUrls);

        }


        /// <summary>
        /// Test the method 'equalsTrue'
        /// </summary>

        [Fact]
        public void equalsTrueTest()
        {
            MessageResult test1 = new MessageResult();
            test1.Uri = "TS";
            test1.DateCreated = "TS";
            test1.DateUpdated = "TS";
            test1.Revision = 1;
            test1.AccountId = "TS";
            test1.MessageId = "TS";
            test1.Status = MessageStatus.NEW;
            test1.From = "TS";
            test1.To = "TS";
            test1.Text = "TS";
            test1.Direction = "TS";
            test1.NotificationUrl = "TS";
            test1.BrandId = "TS";
            test1.CampaignId = "TS";

            MessageResult test2 = new MessageResult();
            test2.Uri = "TS";
            test2.DateCreated = "TS";
            test2.DateUpdated = "TS";
            test2.Revision = 1;
            test2.AccountId = "TS";
            test2.MessageId = "TS";
            test2.Status = MessageStatus.NEW;
            test2.From = "TS";
            test2.To = "TS";
            test2.Text = "TS";
            test2.Direction = "TS";
            test2.NotificationUrl = "TS";
            test2.BrandId = "TS";
            test2.CampaignId = "TS";

            Assert.Equal(test1, test2);
        }

        /// <summary>
        /// Test the method 'equalsFalse'
        /// </summary>

        [Fact]
        public void equalsFalseTest()
        {
            MessageResult test1 = new MessageResult();
            test1.Uri = "TS";
            test1.DateCreated = "TS";
            test1.DateUpdated = "TS";
            test1.Revision = 1;
            test1.AccountId = "TS";
            test1.MessageId = "TS";
            test1.Status = MessageStatus.NEW;
            test1.From = "TS";
            test1.To = "TS";
            test1.Text = "TS";
            test1.Direction = "TS";
            test1.NotificationUrl = "TS";
            test1.BrandId = "TS";
            test1.CampaignId = "TS";

            MessageResult test2 = new MessageResult();
            test2.Uri = "ts";
            test2.DateCreated = "ts";
            test2.DateUpdated = "ts";
            test2.Revision = 2;
            test2.AccountId = "ts";
            test2.MessageId = "ts";
            test2.Status = MessageStatus.QUEUED;
            test2.From = "ts";
            test2.To = "ts";
            test2.Text = "ts";
            test2.Direction = "ts";
            test2.NotificationUrl = "ts";
            test2.BrandId = "ts";
            test2.CampaignId = "ts";

            Assert.NotEqual(test1, test2);
        }

        /// <summary>
        /// Test the method 'hashCodeType'
        /// </summary>

        [Fact]
        public void hashCodeTypeTest()
        {
            MessageResult test1 = new MessageResult();
            test1.Uri = "TS";
            test1.DateCreated = "TS";
            test1.DateUpdated = "TS";
            test1.Revision = 1;
            test1.AccountId = "TS";
            test1.MessageId = "TS";
            test1.Status = MessageStatus.NEW;
            test1.From = "TS";
            test1.To = "TS";
            test1.Text = "TS";
            test1.Direction = "TS";
            test1.NotificationUrl = "TS";
            test1.BrandId = "TS";
            test1.CampaignId = "TS";

            int hashCode1 = test1.GetHashCode();
            Assert.True(hashCode1.GetType() == typeof(int));

        }

        /// <summary>
        /// Test the method 'ToStringType'
        /// </summary>

        [Fact]
        public void ToStringTypeTest()
        {
            MessageResult test1 = new MessageResult();
            test1.Uri = "TS";
            test1.DateCreated = "TS";
            test1.DateUpdated = "TS";
            test1.Revision = 1;
            test1.AccountId = "TS";
            test1.MessageId = "TS";
            test1.Status = MessageStatus.NEW;
            test1.From = "TS";
            test1.To = "TS";
            test1.Text = "TS";
            test1.Direction = "TS";
            test1.NotificationUrl = "TS";
            test1.BrandId = "TS";
            test1.CampaignId = "TS";

            string toString1 = test1.ToString();
            Assert.True(toString1.GetType() == typeof(string));

        }

        /// <summary>
        /// Test the method 'ToStringEquals'
        /// </summary>

        [Fact]
        public void ToStringEqualsTest()
        {
            MessageResult test1 = new MessageResult();
            test1.Uri = "TS";
            test1.DateCreated = "TS";
            test1.DateUpdated = "TS";
            test1.Revision = 1;
            test1.AccountId = "TS";
            test1.MessageId = "TS";
            test1.Status = MessageStatus.NEW;
            test1.From = "TS";
            test1.To = "TS";
            test1.Text = "TS";
            test1.Direction = "TS";
            test1.NotificationUrl = "TS";
            test1.BrandId = "TS";
            test1.CampaignId = "TS";

            MessageResult test2 = new MessageResult();
            test2.Uri = "TS";
            test2.DateCreated = "TS";
            test2.DateUpdated = "TS";
            test2.Revision = 1;
            test2.AccountId = "TS";
            test2.MessageId = "TS";
            test2.Status = MessageStatus.NEW;
            test2.From = "TS";
            test2.To = "TS";
            test2.Text = "TS";
            test2.Direction = "TS";
            test2.NotificationUrl = "TS";
            test2.BrandId = "TS";
            test2.CampaignId = "TS";

            string toString1 = test1.ToString();
            string toString2 = test2.ToString();
            Assert.Equal(toString1, toString2);

        }

        /// <summary>
        /// Test the method 'equals'
        /// </summary>

        [Fact]
        public void equalsTest()
        {
            MessageResult test1 = new MessageResult();
            test1.Uri = "TS";
            test1.DateCreated = "TS";
            test1.DateUpdated = "TS";
            test1.Revision = 1;
            test1.AccountId = "TS";
            test1.MessageId = "TS";
            test1.Status = MessageStatus.NEW;
            test1.From = "TS";
            test1.To = "TS";
            test1.Text = "TS";
            test1.Direction = "TS";
            test1.NotificationUrl = "TS";
            test1.BrandId = "TS";
            test1.CampaignId = "TS";

            MessageResult test2 = new MessageResult();
            test2.Uri = "TS";
            test2.DateCreated = "TS";
            test2.DateUpdated = "TS";
            test2.Revision = 1;
            test2.AccountId = "TS";
            test2.MessageId = "TS";
            test2.Status = MessageStatus.NEW;
            test2.From = "TS";
            test2.To = "TS";
            test2.Text = "TS";
            test2.Direction = "TS";
            test2.NotificationUrl = "TS";
            test2.BrandId = "TS";
            test2.CampaignId = "TS";

            Assert.True(test1.Equals(test2));
        }

        /// <summary>
        /// Test the method 'ToJson'
        /// </summary>

        [Fact]
        public void ToJsonTest()
        {
            MessageResult test1 = new MessageResult();
            test1.Uri = "TS";
            test1.DateCreated = "TS";
            test1.DateUpdated = "TS";
            test1.Revision = 1;
            test1.AccountId = "TS";
            test1.MessageId = "TS";
            test1.Status = MessageStatus.NEW;
            test1.From = "TS";
            test1.To = "TS";
            test1.Text = "TS";
            test1.Direction = "TS";
            test1.NotificationUrl = "TS";
            test1.BrandId = "TS";
            test1.CampaignId = "TS";
            string jsonStr = JsonConvert.SerializeObject(test1, Newtonsoft.Json.Formatting.Indented);

            MessageResult test2 = new MessageResult();
            test2.Uri = "TS";
            test2.DateCreated = "TS";
            test2.DateUpdated = "TS";
            test2.Revision = 1;
            test2.AccountId = "TS";
            test2.MessageId = "TS";
            test2.Status = MessageStatus.NEW;
            test2.From = "TS";
            test2.To = "TS";
            test2.Text = "TS";
            test2.Direction = "TS";
            test2.NotificationUrl = "TS";
            test2.BrandId = "TS";
            test2.CampaignId = "TS";

            Assert.True(jsonStr.Equals(test2.ToJson()));
        }
    }
}
