/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing QueueMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class QueueMemberTests : IDisposable
    {
        private QueueMember instance;

        public QueueMemberTests()
        {
            instance = new QueueMember(
                uri: (string)TestHelpers.getTestValue(typeof(string)),
                callId: (string)TestHelpers.getTestValue(typeof(string)),
                waitTime: (int?)TestHelpers.getTestValue(typeof(int?)),
                position: (int?)TestHelpers.getTestValue(typeof(int?)),
                dateEnqueued: (string)TestHelpers.getTestValue(typeof(string))
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueueMember
        /// </summary>
        [Fact]
        public void QueueMemberInstanceTest()
        {
            Assert.IsType<QueueMember>(instance);
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            instance.Uri = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Uri);
        }

        /// <summary>
        /// Test the property 'CallId'
        /// </summary>
        [Fact]
        public void CallIdTest()
        {
            instance.CallId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CallId);
        }

        /// <summary>
        /// Test the property 'WaitTime'
        /// </summary>
        [Fact]
        public void WaitTimeTest()
        {
            instance.WaitTime = 1;
            Assert.Equal(1, (int)instance.WaitTime);
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            instance.Position = 1;
            Assert.Equal(1, (int)instance.Position);
        }

        /// <summary>
        /// Test the property 'DateEnqueued'
        /// </summary>
        [Fact]
        public void DateEnqueuedTest()
        {
            instance.DateEnqueued = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.DateEnqueued);
        }

        /// <summary>
        /// Test serialize a QueueMember to JSON string - all values are present
        /// </summary>
        [Fact]
        public void QueueMemberSerializeToJSONTest()
        {
            string json = instance.ToJson();
            //Console.WriteLine("++QueueMember++" );
            //Console.WriteLine(json);

            //Console.WriteLine("does it contain - uri ++ " + json.Contains("uri"));
            Assert.Contains("uri", json);

            //Console.WriteLine("does it contain - callId ++ " + json.Contains("callId"));
            Assert.Contains("callId", json);

            //Console.WriteLine("does it contain - waitTime ++ " + json.Contains("waitTime"));
            Assert.Contains("waitTime", json);

            //Console.WriteLine("does it contain - position ++ " + json.Contains("position"));
            Assert.Contains("position", json);

            //Console.WriteLine("does it contain - dateEnqueued ++ " + json.Contains("dateEnqueued"));
            Assert.Contains("dateEnqueued", json);
        }

        /// <summary>
        /// Test serialize a QueueMember to JSON string - null values are stripped
        /// </summary>
        [Fact]
        public void QueueMemberSerializeToJSONStripNullTest()
        {
            instance.Uri = null;

            instance.CallId = null;

            instance.WaitTime = null;

            instance.Position = null;

            instance.DateEnqueued = null;

            string json = instance.ToJson();
            Assert.DoesNotContain("null", json);
        }
    }
}
