/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using freeclimb.Api;
using freeclimb.Model;
using freeclimb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing QueueMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueueMemberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueueMember
        //private QueueMember instance;

        public QueueMemberTests()
        {
            // TODO uncomment below to create an instance of QueueMember
            //instance = new QueueMember();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueueMember
        /// </summary>
        [Fact]
        public void QueueMemberInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueueMember
            //Assert.IsType<QueueMember>(instance);
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'CallId'
        /// </summary>
        [Fact]
        public void CallIdTest()
        {
            // TODO unit test for the property 'CallId'
        }
        /// <summary>
        /// Test the property 'WaitTime'
        /// </summary>
        [Fact]
        public void WaitTimeTest()
        {
            // TODO unit test for the property 'WaitTime'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'DateEnqueued'
        /// </summary>
        [Fact]
        public void DateEnqueuedTest()
        {
            // TODO unit test for the property 'DateEnqueued'
        }

    }

}
