/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing SMSTenDLCCampaign
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class SMSTenDLCCampaignTests : IDisposable
    {
        private SMSTenDLCCampaign instance;

        public SMSTenDLCCampaignTests()
        {
            instance = new SMSTenDLCCampaign(
                accountId: (string)TestHelpers.getTestValue(typeof(string)),
                campaignId: (string)TestHelpers.getTestValue(typeof(string)),
                cspId: (string)TestHelpers.getTestValue(typeof(string)),
                resellerId: (string)TestHelpers.getTestValue(typeof(string)),
                status: (SMSTenDLCCampaignStatus)
                    TestHelpers.getTestValue(typeof(SMSTenDLCCampaignStatus)),
                createDate: (DateTime)TestHelpers.getTestValue(typeof(DateTime)),
                autoRenewal: (bool)TestHelpers.getTestValue(typeof(bool)),
                billedDate: (DateTime?)TestHelpers.getTestValue(typeof(DateTime?)),
                brandId: (string)TestHelpers.getTestValue(typeof(string)),
                usecase: (string)TestHelpers.getTestValue(typeof(string)),
                subUsecases: (List<string>)TestHelpers.getTestValue(typeof(List<string>)),
                description: (string)TestHelpers.getTestValue(typeof(string)),
                embeddedLink: (bool)TestHelpers.getTestValue(typeof(bool)),
                embeddedPhone: (bool)TestHelpers.getTestValue(typeof(bool)),
                affiliateMarketing: (bool)TestHelpers.getTestValue(typeof(bool)),
                numberPool: (bool)TestHelpers.getTestValue(typeof(bool)),
                ageGated: (bool)TestHelpers.getTestValue(typeof(bool)),
                directLending: (bool)TestHelpers.getTestValue(typeof(bool)),
                subscriberOptin: (bool)TestHelpers.getTestValue(typeof(bool)),
                subscriberOptout: (bool)TestHelpers.getTestValue(typeof(bool)),
                subscriberHelp: (bool)TestHelpers.getTestValue(typeof(bool)),
                sample1: (string)TestHelpers.getTestValue(typeof(string)),
                sample2: (string)TestHelpers.getTestValue(typeof(string)),
                sample3: (string)TestHelpers.getTestValue(typeof(string)),
                sample4: (string)TestHelpers.getTestValue(typeof(string)),
                sample5: (string)TestHelpers.getTestValue(typeof(string)),
                messageFlow: (string)TestHelpers.getTestValue(typeof(string)),
                helpMessage: (string)TestHelpers.getTestValue(typeof(string)),
                optinKeywords: (string)TestHelpers.getTestValue(typeof(string)),
                optoutKeywords: (string)TestHelpers.getTestValue(typeof(string)),
                helpKeywords: (string)TestHelpers.getTestValue(typeof(string)),
                optinMessage: (string)TestHelpers.getTestValue(typeof(string)),
                optoutMessage: (string)TestHelpers.getTestValue(typeof(string)),
                referenceId: (string)TestHelpers.getTestValue(typeof(string)),
                mock: (bool)TestHelpers.getTestValue(typeof(bool)),
                nextRenewalOrExpirationDate: (DateOnly?)TestHelpers.getTestValue(typeof(DateOnly?))
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SMSTenDLCCampaign
        /// </summary>
        [Fact]
        public void SMSTenDLCCampaignInstanceTest()
        {
            Assert.IsType<SMSTenDLCCampaign>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            instance.AccountId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.AccountId);
        }

        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            instance.CampaignId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CampaignId);
        }

        /// <summary>
        /// Test the property 'CspId'
        /// </summary>
        [Fact]
        public void CspIdTest()
        {
            instance.CspId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CspId);
        }

        /// <summary>
        /// Test the property 'ResellerId'
        /// </summary>
        [Fact]
        public void ResellerIdTest()
        {
            instance.ResellerId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ResellerId);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            instance.Status = SMSTenDLCCampaignStatus.ACTIVE;
            Assert.Equal(SMSTenDLCCampaignStatus.ACTIVE, instance.Status);
            instance.Status = SMSTenDLCCampaignStatus.EXPIRED;
            Assert.Equal(SMSTenDLCCampaignStatus.EXPIRED, instance.Status);
        }

        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Fact]
        public void CreateDateTest()
        {
            instance.CreateDate = DateTime.Parse("2022-07-05T15:17:05+00:00");
            Assert.Equal(DateTime.Parse("2022-07-05T15:17:05+00:00"), instance.CreateDate);
        }

        /// <summary>
        /// Test the property 'AutoRenewal'
        /// </summary>
        [Fact]
        public void AutoRenewalTest()
        {
            instance.AutoRenewal = false;
            Assert.False(instance.AutoRenewal);
        }

        /// <summary>
        /// Test the property 'BilledDate'
        /// </summary>
        [Fact]
        public void BilledDateTest()
        {
            instance.BilledDate = DateTime.Parse("2022-07-05T15:17:05+00:00");
            Assert.Equal(DateTime.Parse("2022-07-05T15:17:05+00:00"), instance.BilledDate);
        }

        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [Fact]
        public void BrandIdTest()
        {
            instance.BrandId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.BrandId);
        }

        /// <summary>
        /// Test the property 'Usecase'
        /// </summary>
        [Fact]
        public void UsecaseTest()
        {
            instance.Usecase = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Usecase);
        }

        /// <summary>
        /// Test the property 'SubUsecases'
        /// </summary>
        [Fact]
        public void SubUsecasesTest()
        {
            List<string> testList = new List<string>();
            instance.SubUsecases = testList;
            Assert.Equal(testList, instance.SubUsecases);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            instance.Description = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Description);
        }

        /// <summary>
        /// Test the property 'EmbeddedLink'
        /// </summary>
        [Fact]
        public void EmbeddedLinkTest()
        {
            instance.EmbeddedLink = false;
            Assert.False(instance.EmbeddedLink);
        }

        /// <summary>
        /// Test the property 'EmbeddedPhone'
        /// </summary>
        [Fact]
        public void EmbeddedPhoneTest()
        {
            instance.EmbeddedPhone = false;
            Assert.False(instance.EmbeddedPhone);
        }

        /// <summary>
        /// Test the property 'AffiliateMarketing'
        /// </summary>
        [Fact]
        public void AffiliateMarketingTest()
        {
            instance.AffiliateMarketing = false;
            Assert.False(instance.AffiliateMarketing);
        }

        /// <summary>
        /// Test the property 'NumberPool'
        /// </summary>
        [Fact]
        public void NumberPoolTest()
        {
            instance.NumberPool = false;
            Assert.False(instance.NumberPool);
        }

        /// <summary>
        /// Test the property 'AgeGated'
        /// </summary>
        [Fact]
        public void AgeGatedTest()
        {
            instance.AgeGated = false;
            Assert.False(instance.AgeGated);
        }

        /// <summary>
        /// Test the property 'DirectLending'
        /// </summary>
        [Fact]
        public void DirectLendingTest()
        {
            instance.DirectLending = false;
            Assert.False(instance.DirectLending);
        }

        /// <summary>
        /// Test the property 'SubscriberOptin'
        /// </summary>
        [Fact]
        public void SubscriberOptinTest()
        {
            instance.SubscriberOptin = false;
            Assert.False(instance.SubscriberOptin);
        }

        /// <summary>
        /// Test the property 'SubscriberOptout'
        /// </summary>
        [Fact]
        public void SubscriberOptoutTest()
        {
            instance.SubscriberOptout = false;
            Assert.False(instance.SubscriberOptout);
        }

        /// <summary>
        /// Test the property 'SubscriberHelp'
        /// </summary>
        [Fact]
        public void SubscriberHelpTest()
        {
            instance.SubscriberHelp = false;
            Assert.False(instance.SubscriberHelp);
        }

        /// <summary>
        /// Test the property 'Sample1'
        /// </summary>
        [Fact]
        public void Sample1Test()
        {
            instance.Sample1 = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Sample1);
        }

        /// <summary>
        /// Test the property 'Sample2'
        /// </summary>
        [Fact]
        public void Sample2Test()
        {
            instance.Sample2 = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Sample2);
        }

        /// <summary>
        /// Test the property 'Sample3'
        /// </summary>
        [Fact]
        public void Sample3Test()
        {
            instance.Sample3 = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Sample3);
        }

        /// <summary>
        /// Test the property 'Sample4'
        /// </summary>
        [Fact]
        public void Sample4Test()
        {
            instance.Sample4 = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Sample4);
        }

        /// <summary>
        /// Test the property 'Sample5'
        /// </summary>
        [Fact]
        public void Sample5Test()
        {
            instance.Sample5 = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Sample5);
        }

        /// <summary>
        /// Test the property 'MessageFlow'
        /// </summary>
        [Fact]
        public void MessageFlowTest()
        {
            instance.MessageFlow = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.MessageFlow);
        }

        /// <summary>
        /// Test the property 'HelpMessage'
        /// </summary>
        [Fact]
        public void HelpMessageTest()
        {
            instance.HelpMessage = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.HelpMessage);
        }

        /// <summary>
        /// Test the property 'OptinKeywords'
        /// </summary>
        [Fact]
        public void OptinKeywordsTest()
        {
            instance.OptinKeywords = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.OptinKeywords);
        }

        /// <summary>
        /// Test the property 'OptoutKeywords'
        /// </summary>
        [Fact]
        public void OptoutKeywordsTest()
        {
            instance.OptoutKeywords = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.OptoutKeywords);
        }

        /// <summary>
        /// Test the property 'HelpKeywords'
        /// </summary>
        [Fact]
        public void HelpKeywordsTest()
        {
            instance.HelpKeywords = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.HelpKeywords);
        }

        /// <summary>
        /// Test the property 'OptinMessage'
        /// </summary>
        [Fact]
        public void OptinMessageTest()
        {
            instance.OptinMessage = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.OptinMessage);
        }

        /// <summary>
        /// Test the property 'OptoutMessage'
        /// </summary>
        [Fact]
        public void OptoutMessageTest()
        {
            instance.OptoutMessage = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.OptoutMessage);
        }

        /// <summary>
        /// Test the property 'ReferenceId'
        /// </summary>
        [Fact]
        public void ReferenceIdTest()
        {
            instance.ReferenceId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ReferenceId);
        }

        /// <summary>
        /// Test the property 'Mock'
        /// </summary>
        [Fact]
        public void MockTest()
        {
            instance.Mock = false;
            Assert.False(instance.Mock);
        }

        /// <summary>
        /// Test the property 'NextRenewalOrExpirationDate'
        /// </summary>
        [Fact]
        public void NextRenewalOrExpirationDateTest()
        {
            instance.NextRenewalOrExpirationDate = DateOnly.FromDateTime(
                DateTime.Parse("2000-01-01")
            );
            Assert.Equal(
                DateOnly.FromDateTime(DateTime.Parse("2000-01-01")),
                instance.NextRenewalOrExpirationDate
            );
        }

        /// <summary>
        /// Test serialize a SMSTenDLCCampaign to JSON string - all values are present
        /// </summary>
        [Fact]
        public void SMSTenDLCCampaignSerializeToJSONTest()
        {
            string json = instance.ToJson();
            //Console.WriteLine("++SMSTenDLCCampaign++" );
            //Console.WriteLine(json);

            //Console.WriteLine("does it contain - accountId ++ " + json.Contains("accountId"));
            Assert.Contains("accountId", json);

            //Console.WriteLine("does it contain - campaignId ++ " + json.Contains("campaignId"));
            Assert.Contains("campaignId", json);

            //Console.WriteLine("does it contain - cspId ++ " + json.Contains("cspId"));
            Assert.Contains("cspId", json);

            //Console.WriteLine("does it contain - resellerId ++ " + json.Contains("resellerId"));
            Assert.Contains("resellerId", json);

            //Console.WriteLine("does it contain - status ++ " + json.Contains("status"));
            Assert.Contains("status", json);

            //Console.WriteLine("does it contain - createDate ++ " + json.Contains("createDate"));
            Assert.Contains("createDate", json);

            //Console.WriteLine("does it contain - autoRenewal ++ " + json.Contains("autoRenewal"));
            Assert.Contains("autoRenewal", json);

            //Console.WriteLine("does it contain - billedDate ++ " + json.Contains("billedDate"));
            Assert.Contains("billedDate", json);

            //Console.WriteLine("does it contain - brandId ++ " + json.Contains("brandId"));
            Assert.Contains("brandId", json);

            //Console.WriteLine("does it contain - usecase ++ " + json.Contains("usecase"));
            Assert.Contains("usecase", json);

            //Console.WriteLine("does it contain - subUsecases ++ " + json.Contains("subUsecases"));
            Assert.Contains("subUsecases", json);

            //Console.WriteLine("does it contain - description ++ " + json.Contains("description"));
            Assert.Contains("description", json);

            //Console.WriteLine("does it contain - embeddedLink ++ " + json.Contains("embeddedLink"));
            Assert.Contains("embeddedLink", json);

            //Console.WriteLine("does it contain - embeddedPhone ++ " + json.Contains("embeddedPhone"));
            Assert.Contains("embeddedPhone", json);

            //Console.WriteLine("does it contain - affiliateMarketing ++ " + json.Contains("affiliateMarketing"));
            Assert.Contains("affiliateMarketing", json);

            //Console.WriteLine("does it contain - numberPool ++ " + json.Contains("numberPool"));
            Assert.Contains("numberPool", json);

            //Console.WriteLine("does it contain - ageGated ++ " + json.Contains("ageGated"));
            Assert.Contains("ageGated", json);

            //Console.WriteLine("does it contain - directLending ++ " + json.Contains("directLending"));
            Assert.Contains("directLending", json);

            //Console.WriteLine("does it contain - subscriberOptin ++ " + json.Contains("subscriberOptin"));
            Assert.Contains("subscriberOptin", json);

            //Console.WriteLine("does it contain - subscriberOptout ++ " + json.Contains("subscriberOptout"));
            Assert.Contains("subscriberOptout", json);

            //Console.WriteLine("does it contain - subscriberHelp ++ " + json.Contains("subscriberHelp"));
            Assert.Contains("subscriberHelp", json);

            //Console.WriteLine("does it contain - sample1 ++ " + json.Contains("sample1"));
            Assert.Contains("sample1", json);

            //Console.WriteLine("does it contain - sample2 ++ " + json.Contains("sample2"));
            Assert.Contains("sample2", json);

            //Console.WriteLine("does it contain - sample3 ++ " + json.Contains("sample3"));
            Assert.Contains("sample3", json);

            //Console.WriteLine("does it contain - sample4 ++ " + json.Contains("sample4"));
            Assert.Contains("sample4", json);

            //Console.WriteLine("does it contain - sample5 ++ " + json.Contains("sample5"));
            Assert.Contains("sample5", json);

            //Console.WriteLine("does it contain - messageFlow ++ " + json.Contains("messageFlow"));
            Assert.Contains("messageFlow", json);

            //Console.WriteLine("does it contain - helpMessage ++ " + json.Contains("helpMessage"));
            Assert.Contains("helpMessage", json);

            //Console.WriteLine("does it contain - optinKeywords ++ " + json.Contains("optinKeywords"));
            Assert.Contains("optinKeywords", json);

            //Console.WriteLine("does it contain - optoutKeywords ++ " + json.Contains("optoutKeywords"));
            Assert.Contains("optoutKeywords", json);

            //Console.WriteLine("does it contain - helpKeywords ++ " + json.Contains("helpKeywords"));
            Assert.Contains("helpKeywords", json);

            //Console.WriteLine("does it contain - optinMessage ++ " + json.Contains("optinMessage"));
            Assert.Contains("optinMessage", json);

            //Console.WriteLine("does it contain - optoutMessage ++ " + json.Contains("optoutMessage"));
            Assert.Contains("optoutMessage", json);

            //Console.WriteLine("does it contain - referenceId ++ " + json.Contains("referenceId"));
            Assert.Contains("referenceId", json);

            //Console.WriteLine("does it contain - mock ++ " + json.Contains("mock"));
            Assert.Contains("mock", json);

            //Console.WriteLine("does it contain - nextRenewalOrExpirationDate ++ " + json.Contains("nextRenewalOrExpirationDate"));
            Assert.Contains("nextRenewalOrExpirationDate", json);
        }

        /// <summary>
        /// Test serialize a SMSTenDLCCampaign to JSON string - null values are stripped
        /// </summary>
        [Fact]
        public void SMSTenDLCCampaignSerializeToJSONStripNullTest()
        {
            instance.AccountId = null;

            instance.ResellerId = null;

            instance.BilledDate = null;

            instance.Sample2 = null;

            instance.Sample3 = null;

            instance.Sample4 = null;

            instance.Sample5 = null;

            instance.MessageFlow = null;

            instance.HelpMessage = null;

            instance.ReferenceId = null;

            instance.NextRenewalOrExpirationDate = null;

            string json = instance.ToJson();
            Assert.DoesNotContain("null", json);
        }
    }
}
