/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing TranscribeUtterance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class TranscribeUtteranceTests : IDisposable
    {
        private TranscribeUtterance instance;

        public TranscribeUtteranceTests()
        {
            instance = new TranscribeUtterance(
                actionUrl: (string)TestHelpers.getTestValue(typeof(string)),
                playBeep: (bool)TestHelpers.getTestValue(typeof(bool)),
                record: (TranscribeUtteranceRecord)
                    TestHelpers.getTestValue(typeof(TranscribeUtteranceRecord)),
                privacyForLogging: (bool)TestHelpers.getTestValue(typeof(bool)),
                privacyForRecording: (bool)TestHelpers.getTestValue(typeof(bool)),
                prompts: (List<PerclCommand>)TestHelpers.getTestValue(typeof(List<PerclCommand>))
            );
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TranscribeUtterance
        /// </summary>
        [Fact]
        public void TranscribeUtteranceInstanceTest()
        {
            Assert.IsType<TranscribeUtterance>(instance);
        }

        /// <summary>
        /// Test the property 'ActionUrl'
        /// </summary>
        [Fact]
        public void ActionUrlTest()
        {
            instance.ActionUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.ActionUrl);
        }

        /// <summary>
        /// Test the property 'PlayBeep'
        /// </summary>
        [Fact]
        public void PlayBeepTest()
        {
            instance.PlayBeep = false;
            Assert.False(instance.PlayBeep);
        }

        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Fact]
        public void RecordTest()
        {
            TranscribeUtteranceRecord testObject = (TranscribeUtteranceRecord)
                TestHelpers.getTestValue(typeof(TranscribeUtteranceRecord));
            instance.Record = testObject;
            Assert.Equal(testObject, instance.Record);
        }

        /// <summary>
        /// Test the property 'PrivacyForLogging'
        /// </summary>
        [Fact]
        public void PrivacyForLoggingTest()
        {
            instance.PrivacyForLogging = false;
            Assert.False(instance.PrivacyForLogging);
        }

        /// <summary>
        /// Test the property 'PrivacyForRecording'
        /// </summary>
        [Fact]
        public void PrivacyForRecordingTest()
        {
            instance.PrivacyForRecording = false;
            Assert.False(instance.PrivacyForRecording);
        }

        /// <summary>
        /// Test the property 'Prompts'
        /// </summary>
        [Fact]
        public void PromptsTest()
        {
            List<PerclCommand> testList = new List<PerclCommand>();
            instance.Prompts = testList;
            Assert.Equal(instance.Prompts, testList);
        }
    }
}
