/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using freeclimb.Model;
using freeclimb.Client;
using System.Reflection;
using Newtonsoft.Json;

using freeclimb.Enums;

namespace freeclimb.Test.Model
{
    /// <summary>
    ///  Class for testing TranscribeWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranscribeWebhookTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TranscribeWebhook
        private TranscribeWebhook instance;

        public TranscribeWebhookTests()
        {
            instance = new TranscribeWebhook();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TranscribeWebhook
        /// </summary>
        [Fact]
        public void TranscribeWebhookInstanceTest()
        {
            Assert.IsType<TranscribeWebhook>(instance);
        }

        /// <summary>
        /// Test the property 'RequestType'
        /// </summary>
        [Fact]
        public void RequestTypeTest()
        {
            
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            instance.AccountId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.AccountId);
            
        }

        /// <summary>
        /// Test the property 'CallId'
        /// </summary>
        [Fact]
        public void CallIdTest()
        {
            instance.CallId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.CallId);
            
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            instance.From = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.From);
            
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            instance.To = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.To);
            
        }

        /// <summary>
        /// Test the property 'RecordingId'
        /// </summary>
        [Fact]
        public void RecordingIdTest()
        {
            instance.RecordingId = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.RecordingId);
            
        }

        /// <summary>
        /// Test the property 'RecordingUrl'
        /// </summary>
        [Fact]
        public void RecordingUrlTest()
        {
            instance.RecordingUrl = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.RecordingUrl);
            
        }

        /// <summary>
        /// Test the property 'RecordingSize'
        /// </summary>
        [Fact]
        public void RecordingSizeTest()
        {
            
            instance.RecordingSize = 1;
            Assert.Equal(1, (int) instance.RecordingSize);
        }

        /// <summary>
        /// Test the property 'RecordingFormat'
        /// </summary>
        [Fact]
        public void RecordingFormatTest()
        {
            instance.RecordingFormat = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.RecordingFormat);
            
        }

        /// <summary>
        /// Test the property 'RecordingDurationMs'
        /// </summary>
        [Fact]
        public void RecordingDurationMsTest()
        {
            
            instance.RecordingDurationMs = 1;
            Assert.Equal(1, (int) instance.RecordingDurationMs);
        }

        /// <summary>
        /// Test the property 'TermReason'
        /// </summary>
        [Fact]
        public void TermReasonTest()
        {
            instance.TermReason = TranscribeTermReason.ERROR;
            Assert.Equal(instance.TermReason,TranscribeTermReason.ERROR);
            instance.TermReason = TranscribeTermReason.COMPLETED;
            Assert.Equal(instance.TermReason,TranscribeTermReason.COMPLETED);
            
        }

        /// <summary>
        /// Test the property 'RecordTermReason'
        /// </summary>
        [Fact]
        public void RecordTermReasonTest()
        {
            instance.RecordTermReason = RecordUtteranceTermReason.FINISH_KEY;
            Assert.Equal(instance.RecordTermReason,RecordUtteranceTermReason.FINISH_KEY);
            instance.RecordTermReason = RecordUtteranceTermReason.TIMEOUT;
            Assert.Equal(instance.RecordTermReason,RecordUtteranceTermReason.TIMEOUT);
            instance.RecordTermReason = RecordUtteranceTermReason.HANGUP;
            Assert.Equal(instance.RecordTermReason,RecordUtteranceTermReason.HANGUP);
            instance.RecordTermReason = RecordUtteranceTermReason.MAX_LENGTH;
            Assert.Equal(instance.RecordTermReason,RecordUtteranceTermReason.MAX_LENGTH);
            
        }

        /// <summary>
        /// Test the property 'Digit'
        /// </summary>
        [Fact]
        public void DigitTest()
        {
            instance.Digit = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Digit);
            
        }

        /// <summary>
        /// Test the property 'PrivacyForLogging'
        /// </summary>
        [Fact]
        public void PrivacyForLoggingTest()
        {
            instance.PrivacyForLogging = false;
            Assert.Equal(false, instance.PrivacyForLogging);       
            
        }

        /// <summary>
        /// Test the property 'PrivacyForRecording'
        /// </summary>
        [Fact]
        public void PrivacyForRecordingTest()
        {
            instance.PrivacyForRecording = false;
            Assert.Equal(false, instance.PrivacyForRecording);       
            
        }

        /// <summary>
        /// Test the property 'BargeInReason'
        /// </summary>
        [Fact]
        public void BargeInReasonTest()
        {
            instance.BargeInReason = BargeInReason.NO_BARGE_IN;
            Assert.Equal(instance.BargeInReason,BargeInReason.NO_BARGE_IN);
            instance.BargeInReason = BargeInReason.BARGE_IN_BY_DTMF;
            Assert.Equal(instance.BargeInReason,BargeInReason.BARGE_IN_BY_DTMF);
            instance.BargeInReason = BargeInReason.BARGE_IN_BY_ENERGY;
            Assert.Equal(instance.BargeInReason,BargeInReason.BARGE_IN_BY_ENERGY);
            
        }

        /// <summary>
        /// Test the property 'BargedInPromptNo'
        /// </summary>
        [Fact]
        public void BargedInPromptNoTest()
        {
            
            instance.BargedInPromptNo = 1;
            Assert.Equal(1, (int) instance.BargedInPromptNo);
        }

        /// <summary>
        /// Test the property 'BargedInPromptMs'
        /// </summary>
        [Fact]
        public void BargedInPromptMsTest()
        {
            
            instance.BargedInPromptMs = 1;
            Assert.Equal(1, (int) instance.BargedInPromptMs);
        }

        /// <summary>
        /// Test the property 'BargedInPromptLoopNo'
        /// </summary>
        [Fact]
        public void BargedInPromptLoopNoTest()
        {
            
            instance.BargedInPromptLoopNo = 1;
            Assert.Equal(1, (int) instance.BargedInPromptLoopNo);
        }

        /// <summary>
        /// Test the property 'BargeInTimeMs'
        /// </summary>
        [Fact]
        public void BargeInTimeMsTest()
        {
            
            instance.BargeInTimeMs = 1;
            Assert.Equal(1, (int) instance.BargeInTimeMs);
        }

        /// <summary>
        /// Test the property 'Transcript'
        /// </summary>
        [Fact]
        public void TranscriptTest()
        {
            instance.Transcript = "TEST_STRING";
            Assert.Equal("TEST_STRING", instance.Transcript);
            
        }

        /// <summary>
        /// Test the property 'TranscribeReason'
        /// </summary>
        [Fact]
        public void TranscribeReasonTest()
        {
            instance.TranscribeReason = TranscribeReason.INTERNAL_ERROR;
            Assert.Equal(instance.TranscribeReason,TranscribeReason.INTERNAL_ERROR);
            instance.TranscribeReason = TranscribeReason.HANGUP;
            Assert.Equal(instance.TranscribeReason,TranscribeReason.HANGUP);
            instance.TranscribeReason = TranscribeReason.MAX_LENGTH;
            Assert.Equal(instance.TranscribeReason,TranscribeReason.MAX_LENGTH);
            instance.TranscribeReason = TranscribeReason.DIGIT;
            Assert.Equal(instance.TranscribeReason,TranscribeReason.DIGIT);
            instance.TranscribeReason = TranscribeReason.NO_INPUT;
            Assert.Equal(instance.TranscribeReason,TranscribeReason.NO_INPUT);
            
        }

        /// <summary>
        /// Test the property 'TranscriptionDurationMs'
        /// </summary>
        [Fact]
        public void TranscriptionDurationMsTest()
        {
            
            instance.TranscriptionDurationMs = 1;
            Assert.Equal(1, (int) instance.TranscriptionDurationMs);
        }
    }
}
