/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using freeclimb.Client;
using freeclimb.Enums;
using freeclimb.Model;
using freeclimb.Test;
using Newtonsoft.Json;
using Xunit;

namespace freeclimb.Test.Enums
{
    /// <summary>
    ///  Class for testing AccountStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>

    public class AccountStatusTests : IDisposable
    {
        private AccountStatus instance;

        public AccountStatusTests()
        {
            instance = new AccountStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountStatus
        /// </summary>
        [Fact]
        public void AccountStatusInstanceTest()
        {
            Assert.IsType<AccountStatus>(instance);
        }

        [Fact]
        public void TestCLOSEDShouldWork()
        {
            AccountStatus test = AccountStatus.CLOSED;
            Assert.Equal(typeof(AccountStatus), test.GetType());
        }

        [Fact]
        public void TestCLOSEDShouldSerializeToEnum()
        {
            AccountStatus expectedValue = AccountStatus.CLOSED;
            AccountStatus calculatedValue = (AccountStatus)
                Enum.Parse(typeof(AccountStatus), "CLOSED");
            Assert.Equal(expectedValue, calculatedValue);
        }

        [Fact]
        public void TestCLOSEDShouldDeserializeToString()
        {
            AccountStatus test = AccountStatus.CLOSED;
            string expectedValue = "CLOSED";
            string calculatedValue = test.ToString();
            Assert.Equal(expectedValue, calculatedValue);
        }

        [Fact]
        public void TestSUSPENDEDShouldWork()
        {
            AccountStatus test = AccountStatus.SUSPENDED;
            Assert.Equal(typeof(AccountStatus), test.GetType());
        }

        [Fact]
        public void TestSUSPENDEDShouldSerializeToEnum()
        {
            AccountStatus expectedValue = AccountStatus.SUSPENDED;
            AccountStatus calculatedValue = (AccountStatus)
                Enum.Parse(typeof(AccountStatus), "SUSPENDED");
            Assert.Equal(expectedValue, calculatedValue);
        }

        [Fact]
        public void TestSUSPENDEDShouldDeserializeToString()
        {
            AccountStatus test = AccountStatus.SUSPENDED;
            string expectedValue = "SUSPENDED";
            string calculatedValue = test.ToString();
            Assert.Equal(expectedValue, calculatedValue);
        }

        [Fact]
        public void TestACTIVEShouldWork()
        {
            AccountStatus test = AccountStatus.ACTIVE;
            Assert.Equal(typeof(AccountStatus), test.GetType());
        }

        [Fact]
        public void TestACTIVEShouldSerializeToEnum()
        {
            AccountStatus expectedValue = AccountStatus.ACTIVE;
            AccountStatus calculatedValue = (AccountStatus)
                Enum.Parse(typeof(AccountStatus), "ACTIVE");
            Assert.Equal(expectedValue, calculatedValue);
        }

        [Fact]
        public void TestACTIVEShouldDeserializeToString()
        {
            AccountStatus test = AccountStatus.ACTIVE;
            string expectedValue = "ACTIVE";
            string calculatedValue = test.ToString();
            Assert.Equal(expectedValue, calculatedValue);
        }
    }
}
