version: '{build}'
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
deploy:
  - provider: NuGet
    api_key:
      secure: 2lQHYbvMS+t33Lo/HlUDN9u709m6YxwUyDKef/nx/J3bdd0QRis+Iv/MFdIHCQU5
    on:
      appveyor_repo_tag: true