/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using freeclimb.Enums;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = freeclimb.Client.OpenAPIDateConverter;

namespace freeclimb.Model
{
    /// <summary>
    /// The list of subresources for this Call. These include things like logs and recordings associated with the Call.
    /// </summary>
    [DataContract(Name = "CallResult_allOf_subresourceUris")]
    public partial class CallResultAllOfSubresourceUris : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallResultAllOfSubresourceUris" /> class.
        /// </summary>
        /// <param name="logs">The URI for the logs associated with this Call..</param>
        /// <param name="recordings">The URI for the recordings associated with this Call..</param>
        public CallResultAllOfSubresourceUris(
            string logs = default(string),
            string recordings = default(string)
        )
        {
            this.Logs = logs;

            this.Recordings = recordings;
        }

        /// <summary>
        /// The URI for the logs associated with this Call.
        /// </summary>
        /// <value>The URI for the logs associated with this Call.</value>
        [DataMember(Name = "logs", EmitDefaultValue = false)]
        public string Logs { get; set; }

        /// <summary>
        /// The URI for the recordings associated with this Call.
        /// </summary>
        /// <value>The URI for the recordings associated with this Call.</value>
        [DataMember(Name = "recordings", EmitDefaultValue = false)]
        public string Recordings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CallResultAllOfSubresourceUris {\n");
            sb.Append("  Logs: ").Append(Logs).Append("\n");
            sb.Append("  Recordings: ").Append(Recordings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(
                this,
                Newtonsoft.Json.Formatting.Indented,
                new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }
            );
        }

        /// <summary>
        /// Retrieve the KVP Dictionary for the CallResultAllOfSubresourceUris instance.
        /// </summary>
        /// <returns>KVP Dictionary</returns>
        public virtual IDictionary<string, object> ToKvp()
        {
            IDictionary<string, object> props = new Dictionary<string, object>();
            AddToDictionary(props, "logs", Logs);
            AddToDictionary(props, "recordings", Recordings);
            return props;
        }

        private IDictionary<string, object> AddToDictionary(
            IDictionary<string, object> dict,
            string key,
            object value
        )
        {
            if (value != null)
            {
                dict.Add(key, value);
            }
            return dict;
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext
        )
        {
            yield break;
        }
    }
}
