/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = freeclimb.Client.OpenAPIDateConverter;
using freeclimb.Enums;

namespace freeclimb.Model
{
    /// <summary>
    /// CallResultAllOf
    /// </summary>
    [DataContract(Name = "CallResult_allOf")]
    public partial class CallResultAllOf : IEquatable<CallResultAllOf>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets CallStatus
        /// </summary>
        [DataMember(Name = "callStatus", EmitDefaultValue = true)]
        public CallStatus? CallStatus { get; set; }

        /// <summary>
        /// Gets or Sets Direction
        /// </summary>
        [DataMember(Name = "direction", EmitDefaultValue = true)]
        public CallDirection? Direction { get; set; }

        /// <summary>
        /// Gets or Sets AnsweredBy
        /// </summary>
        [DataMember(Name = "answeredBy", EmitDefaultValue = true)]
        public AnsweredBy? AnsweredBy { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CallResultAllOf" /> class.
        /// </summary>
        /// <param name="callId">String that uniquely identifies this Call resource..</param>
        /// <param name="parentCallId">ID of the Call that created this leg (child Call)..</param>
        /// <param name="accountId">ID of the account that owns this Call..</param>
        /// <param name="from">Phone number that initiated this Call..</param>
        /// <param name="to">Phone number that received this Call..</param>
        /// <param name="phoneNumberId">If the Call was inbound, this is the ID of the IncomingPhoneNumber that received the Call (DNIS). If the Call was outbound, this is the ID of the phone number from which the Call was placed (ANI)..</param>
        /// <param name="callStatus">callStatus.</param>
        /// <param name="startTime">Start time of the Call (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call has not yet been dialed..</param>
        /// <param name="connectTime">Time the Call was answered (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call has not yet been dialed..</param>
        /// <param name="endTime">End time of the Call (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call did not complete successfully..</param>
        /// <param name="duration">Total length of the Call in seconds. Measures time between startTime and endTime. This value is empty for busy, failed, unanswered or ongoing Calls..</param>
        /// <param name="connectDuration">Length of time that the Call was connected in seconds. Measures time between connectTime and endTime. This value is empty for busy, failed, unanswered or ongoing Calls..</param>
        /// <param name="direction">direction.</param>
        /// <param name="answeredBy">answeredBy.</param>
        /// <param name="subresourceUris">The list of subresources for this Call. These include things like logs and recordings associated with the Call..</param>
        public CallResultAllOf(string callId = default(string), string parentCallId = default(string), string accountId = default(string), string from = default(string), string to = default(string), string phoneNumberId = default(string), CallStatus? callStatus = default(CallStatus?), string startTime = default(string), string connectTime = default(string), string endTime = default(string), int? duration = default(int?), int? connectDuration = default(int?), CallDirection? direction = default(CallDirection?), AnsweredBy? answeredBy = default(AnsweredBy?), Object subresourceUris = default(Object))
        {
            this.CallId = callId;
            this.ParentCallId = parentCallId;
            this.AccountId = accountId;
            this.From = from;
            this.To = to;
            this.PhoneNumberId = phoneNumberId;
            this.CallStatus = callStatus;
            this.StartTime = startTime;
            this.ConnectTime = connectTime;
            this.EndTime = endTime;
            this.Duration = duration;
            this.ConnectDuration = connectDuration;
            this.Direction = direction;
            this.AnsweredBy = answeredBy;
            this.SubresourceUris = subresourceUris;
        }

        /// <summary>
        /// String that uniquely identifies this Call resource.
        /// </summary>
        /// <value>String that uniquely identifies this Call resource.</value>
        [DataMember(Name = "callId", EmitDefaultValue = true)]
        public string CallId { get; set; }

        /// <summary>
        /// ID of the Call that created this leg (child Call).
        /// </summary>
        /// <value>ID of the Call that created this leg (child Call).</value>
        [DataMember(Name = "parentCallId", EmitDefaultValue = true)]
        public string ParentCallId { get; set; }

        /// <summary>
        /// ID of the account that owns this Call.
        /// </summary>
        /// <value>ID of the account that owns this Call.</value>
        [DataMember(Name = "accountId", EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Phone number that initiated this Call.
        /// </summary>
        /// <value>Phone number that initiated this Call.</value>
        [DataMember(Name = "from", EmitDefaultValue = true)]
        public string From { get; set; }

        /// <summary>
        /// Phone number that received this Call.
        /// </summary>
        /// <value>Phone number that received this Call.</value>
        [DataMember(Name = "to", EmitDefaultValue = true)]
        public string To { get; set; }

        /// <summary>
        /// If the Call was inbound, this is the ID of the IncomingPhoneNumber that received the Call (DNIS). If the Call was outbound, this is the ID of the phone number from which the Call was placed (ANI).
        /// </summary>
        /// <value>If the Call was inbound, this is the ID of the IncomingPhoneNumber that received the Call (DNIS). If the Call was outbound, this is the ID of the phone number from which the Call was placed (ANI).</value>
        [DataMember(Name = "phoneNumberId", EmitDefaultValue = true)]
        public string PhoneNumberId { get; set; }

        /// <summary>
        /// Start time of the Call (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call has not yet been dialed.
        /// </summary>
        /// <value>Start time of the Call (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call has not yet been dialed.</value>
        [DataMember(Name = "startTime", EmitDefaultValue = true)]
        public string StartTime { get; set; }

        /// <summary>
        /// Time the Call was answered (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call has not yet been dialed.
        /// </summary>
        /// <value>Time the Call was answered (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call has not yet been dialed.</value>
        [DataMember(Name = "connectTime", EmitDefaultValue = true)]
        public string ConnectTime { get; set; }

        /// <summary>
        /// End time of the Call (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call did not complete successfully.
        /// </summary>
        /// <value>End time of the Call (GMT) in RFC 1123 format (e.g., Mon, 15 Jun 2009 20:45:30 GMT). Empty if the Call did not complete successfully.</value>
        [DataMember(Name = "endTime", EmitDefaultValue = true)]
        public string EndTime { get; set; }

        /// <summary>
        /// Total length of the Call in seconds. Measures time between startTime and endTime. This value is empty for busy, failed, unanswered or ongoing Calls.
        /// </summary>
        /// <value>Total length of the Call in seconds. Measures time between startTime and endTime. This value is empty for busy, failed, unanswered or ongoing Calls.</value>
        [DataMember(Name = "duration", EmitDefaultValue = true)]
        public int? Duration { get; set; }

        /// <summary>
        /// Length of time that the Call was connected in seconds. Measures time between connectTime and endTime. This value is empty for busy, failed, unanswered or ongoing Calls.
        /// </summary>
        /// <value>Length of time that the Call was connected in seconds. Measures time between connectTime and endTime. This value is empty for busy, failed, unanswered or ongoing Calls.</value>
        [DataMember(Name = "connectDuration", EmitDefaultValue = true)]
        public int? ConnectDuration { get; set; }

        /// <summary>
        /// The list of subresources for this Call. These include things like logs and recordings associated with the Call.
        /// </summary>
        /// <value>The list of subresources for this Call. These include things like logs and recordings associated with the Call.</value>
        [DataMember(Name = "subresourceUris", EmitDefaultValue = true)]
        public Object SubresourceUris { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CallResultAllOf {\n");
            sb.Append("  CallId: ").Append(CallId).Append("\n");
            sb.Append("  ParentCallId: ").Append(ParentCallId).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  PhoneNumberId: ").Append(PhoneNumberId).Append("\n");
            sb.Append("  CallStatus: ").Append(CallStatus).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  ConnectTime: ").Append(ConnectTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  ConnectDuration: ").Append(ConnectDuration).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  AnsweredBy: ").Append(AnsweredBy).Append("\n");
            sb.Append("  SubresourceUris: ").Append(SubresourceUris).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Retrieve the KVP Dictionary for the CallResultAllOf instance. 
        /// </summary>
        /// <returns>KVP Dictionary</returns>
        public virtual IDictionary<string, object> ToKvp()
        {
            IDictionary<string, object> props = new Dictionary<string, object>();
            props.Add("callId", CallId);          
            props.Add("parentCallId", ParentCallId);          
            props.Add("accountId", AccountId);          
            props.Add("from", From);          
            props.Add("to", To);          
            props.Add("phoneNumberId", PhoneNumberId);          
            props.Add("callStatus", CallStatus);          
            props.Add("startTime", StartTime);          
            props.Add("connectTime", ConnectTime);          
            props.Add("endTime", EndTime);          
            props.Add("duration", Duration);          
            props.Add("connectDuration", ConnectDuration);          
            props.Add("direction", Direction);          
            props.Add("answeredBy", AnsweredBy);          
            props.Add("subresourceUris", SubresourceUris);          
            return props;
        }
        
        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CallResultAllOf);
        }

        /// <summary>
        /// Returns true if CallResultAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of CallResultAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallResultAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CallId == input.CallId ||
                    (this.CallId != null &&
                    this.CallId.Equals(input.CallId))
                ) && 
                (
                    this.ParentCallId == input.ParentCallId ||
                    (this.ParentCallId != null &&
                    this.ParentCallId.Equals(input.ParentCallId))
                ) && 
                (
                    this.AccountId == input.AccountId ||
                    (this.AccountId != null &&
                    this.AccountId.Equals(input.AccountId))
                ) && 
                (
                    this.From == input.From ||
                    (this.From != null &&
                    this.From.Equals(input.From))
                ) && 
                (
                    this.To == input.To ||
                    (this.To != null &&
                    this.To.Equals(input.To))
                ) && 
                (
                    this.PhoneNumberId == input.PhoneNumberId ||
                    (this.PhoneNumberId != null &&
                    this.PhoneNumberId.Equals(input.PhoneNumberId))
                ) && 
                (
                    this.CallStatus == input.CallStatus ||
                    this.CallStatus.Equals(input.CallStatus)
                ) && 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.ConnectTime == input.ConnectTime ||
                    (this.ConnectTime != null &&
                    this.ConnectTime.Equals(input.ConnectTime))
                ) && 
                (
                    this.EndTime == input.EndTime ||
                    (this.EndTime != null &&
                    this.EndTime.Equals(input.EndTime))
                ) && 
                (
                    this.Duration == input.Duration ||
                    (this.Duration != null &&
                    this.Duration.Equals(input.Duration))
                ) && 
                (
                    this.ConnectDuration == input.ConnectDuration ||
                    (this.ConnectDuration != null &&
                    this.ConnectDuration.Equals(input.ConnectDuration))
                ) && 
                (
                    this.Direction == input.Direction ||
                    this.Direction.Equals(input.Direction)
                ) && 
                (
                    this.AnsweredBy == input.AnsweredBy ||
                    this.AnsweredBy.Equals(input.AnsweredBy)
                ) && 
                (
                    this.SubresourceUris == input.SubresourceUris ||
                    (this.SubresourceUris != null &&
                    this.SubresourceUris.Equals(input.SubresourceUris))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CallId != null)
                {
                    hashCode = (hashCode * 59) + this.CallId.GetHashCode();
                }
                if (this.ParentCallId != null)
                {
                    hashCode = (hashCode * 59) + this.ParentCallId.GetHashCode();
                }
                if (this.AccountId != null)
                {
                    hashCode = (hashCode * 59) + this.AccountId.GetHashCode();
                }
                if (this.From != null)
                {
                    hashCode = (hashCode * 59) + this.From.GetHashCode();
                }
                if (this.To != null)
                {
                    hashCode = (hashCode * 59) + this.To.GetHashCode();
                }
                if (this.PhoneNumberId != null)
                {
                    hashCode = (hashCode * 59) + this.PhoneNumberId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.CallStatus.GetHashCode();
                if (this.StartTime != null)
                {
                    hashCode = (hashCode * 59) + this.StartTime.GetHashCode();
                }
                if (this.ConnectTime != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectTime.GetHashCode();
                }
                if (this.EndTime != null)
                {
                    hashCode = (hashCode * 59) + this.EndTime.GetHashCode();
                }
                if (this.Duration != null)
                {
                    hashCode = (hashCode * 59) + this.Duration.GetHashCode();
                }
                if (this.ConnectDuration != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectDuration.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Direction.GetHashCode();
                hashCode = (hashCode * 59) + this.AnsweredBy.GetHashCode();
                if (this.SubresourceUris != null)
                {
                    hashCode = (hashCode * 59) + this.SubresourceUris.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
