/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = freeclimb.Client.OpenAPIDateConverter;
using freeclimb.Enums;
using System.Text.Json;

namespace freeclimb.Enums
{
    /// <summary>
    /// Defines Language
    /// </summary>
    public enum Language
    {
        /// <summary>
        /// Enum CATALAN for value: ca-ES
        /// </summary>
        CATALAN = 1,

        /// <summary>
        /// Enum DANISH for value: da-DK
        /// </summary>
        DANISH = 2,

        /// <summary>
        /// Enum GERMAN for value: de-DE
        /// </summary>
        GERMAN = 3,

        /// <summary>
        /// Enum ENGLISH_AU for value: en-AU
        /// </summary>
        ENGLISH_AU = 4,

        /// <summary>
        /// Enum ENGLISH_CA for value: en-CA
        /// </summary>
        ENGLISH_CA = 5,

        /// <summary>
        /// Enum ENGLISH_UK for value: en-GB
        /// </summary>
        ENGLISH_UK = 6,

        /// <summary>
        /// Enum ENGLISH_IN for value: en-IN
        /// </summary>
        ENGLISH_IN = 7,

        /// <summary>
        /// Enum ENGLISH_US for value: en-US
        /// </summary>
        ENGLISH_US = 8,

        /// <summary>
        /// Enum ENGLISH_ES for value: es-ES
        /// </summary>
        ENGLISH_ES = 9,

        /// <summary>
        /// Enum ENGLISH_MX for value: es-MX
        /// </summary>
        ENGLISH_MX = 10,

        /// <summary>
        /// Enum FINNISH for value: fi-FI
        /// </summary>
        FINNISH = 11,

        /// <summary>
        /// Enum FRENCH_CA for value: fr-CA
        /// </summary>
        FRENCH_CA = 12,

        /// <summary>
        /// Enum FRENCH_FR for value: fr-FR
        /// </summary>
        FRENCH_FR = 13,

        /// <summary>
        /// Enum ITALIAN for value: it-IT
        /// </summary>
        ITALIAN = 14,

        /// <summary>
        /// Enum JAPANESE for value: ja-JP
        /// </summary>
        JAPANESE = 15,

        /// <summary>
        /// Enum KOREAN for value: ko-KR
        /// </summary>
        KOREAN = 16,

        /// <summary>
        /// Enum NORWEGIAN for value: nb-NO
        /// </summary>
        NORWEGIAN = 17,

        /// <summary>
        /// Enum DUTCH for value: nl-NL
        /// </summary>
        DUTCH = 18,

        /// <summary>
        /// Enum POLISH for value: pl-PL
        /// </summary>
        POLISH = 19,

        /// <summary>
        /// Enum PORTUGESE_BR for value: pt-BR
        /// </summary>
        PORTUGESE_BR = 20,

        /// <summary>
        /// Enum PORTUGESE_PT for value: pt-PT
        /// </summary>
        PORTUGESE_PT = 21,

        /// <summary>
        /// Enum RUSSIAN for value: ru-RU
        /// </summary>
        RUSSIAN = 22,

        /// <summary>
        /// Enum SWEDISH for value: sv-SE
        /// </summary>
        SWEDISH = 23,

        /// <summary>
        /// Enum CHINESE_CN for value: zh-CN
        /// </summary>
        CHINESE_CN = 24,

        /// <summary>
        /// Enum CHINESE_HK for value: zh-HK
        /// </summary>
        CHINESE_HK = 25,

        /// <summary>
        /// Enum CHINESE_TW for value: zh-TW
        /// </summary>
        CHINESE_TW = 26
    }

    /// <summary>
    /// Converts <see cref="Language"/> to and from the JSON value
    /// </summary>
    public static class LanguageValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="Language"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Language FromString(string value)
        {
            if (value.Equals("ca-ES"))
                return Language.CATALAN;

            if (value.Equals("da-DK"))
                return Language.DANISH;

            if (value.Equals("de-DE"))
                return Language.GERMAN;

            if (value.Equals("en-AU"))
                return Language.ENGLISH_AU;

            if (value.Equals("en-CA"))
                return Language.ENGLISH_CA;

            if (value.Equals("en-GB"))
                return Language.ENGLISH_UK;

            if (value.Equals("en-IN"))
                return Language.ENGLISH_IN;

            if (value.Equals("en-US"))
                return Language.ENGLISH_US;

            if (value.Equals("es-ES"))
                return Language.ENGLISH_ES;

            if (value.Equals("es-MX"))
                return Language.ENGLISH_MX;

            if (value.Equals("fi-FI"))
                return Language.FINNISH;

            if (value.Equals("fr-CA"))
                return Language.FRENCH_CA;

            if (value.Equals("fr-FR"))
                return Language.FRENCH_FR;

            if (value.Equals("it-IT"))
                return Language.ITALIAN;

            if (value.Equals("ja-JP"))
                return Language.JAPANESE;

            if (value.Equals("ko-KR"))
                return Language.KOREAN;

            if (value.Equals("nb-NO"))
                return Language.NORWEGIAN;

            if (value.Equals("nl-NL"))
                return Language.DUTCH;

            if (value.Equals("pl-PL"))
                return Language.POLISH;

            if (value.Equals("pt-BR"))
                return Language.PORTUGESE_BR;

            if (value.Equals("pt-PT"))
                return Language.PORTUGESE_PT;

            if (value.Equals("ru-RU"))
                return Language.RUSSIAN;

            if (value.Equals("sv-SE"))
                return Language.SWEDISH;

            if (value.Equals("zh-CN"))
                return Language.CHINESE_CN;

            if (value.Equals("zh-HK"))
                return Language.CHINESE_HK;

            if (value.Equals("zh-TW"))
                return Language.CHINESE_TW;

            throw new NotImplementedException($"Could not convert value to type Language: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="Language"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Language? FromStringOrDefault(string value)
        {
            if (value.Equals("ca-ES"))
                return Language.CATALAN;

            if (value.Equals("da-DK"))
                return Language.DANISH;

            if (value.Equals("de-DE"))
                return Language.GERMAN;

            if (value.Equals("en-AU"))
                return Language.ENGLISH_AU;

            if (value.Equals("en-CA"))
                return Language.ENGLISH_CA;

            if (value.Equals("en-GB"))
                return Language.ENGLISH_UK;

            if (value.Equals("en-IN"))
                return Language.ENGLISH_IN;

            if (value.Equals("en-US"))
                return Language.ENGLISH_US;

            if (value.Equals("es-ES"))
                return Language.ENGLISH_ES;

            if (value.Equals("es-MX"))
                return Language.ENGLISH_MX;

            if (value.Equals("fi-FI"))
                return Language.FINNISH;

            if (value.Equals("fr-CA"))
                return Language.FRENCH_CA;

            if (value.Equals("fr-FR"))
                return Language.FRENCH_FR;

            if (value.Equals("it-IT"))
                return Language.ITALIAN;

            if (value.Equals("ja-JP"))
                return Language.JAPANESE;

            if (value.Equals("ko-KR"))
                return Language.KOREAN;

            if (value.Equals("nb-NO"))
                return Language.NORWEGIAN;

            if (value.Equals("nl-NL"))
                return Language.DUTCH;

            if (value.Equals("pl-PL"))
                return Language.POLISH;

            if (value.Equals("pt-BR"))
                return Language.PORTUGESE_BR;

            if (value.Equals("pt-PT"))
                return Language.PORTUGESE_PT;

            if (value.Equals("ru-RU"))
                return Language.RUSSIAN;

            if (value.Equals("sv-SE"))
                return Language.SWEDISH;

            if (value.Equals("zh-CN"))
                return Language.CHINESE_CN;

            if (value.Equals("zh-HK"))
                return Language.CHINESE_HK;

            if (value.Equals("zh-TW"))
                return Language.CHINESE_TW;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="Language"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(Language value)
        {
            if (value == Language.CATALAN)
                return "ca-ES";

            if (value == Language.DANISH)
                return "da-DK";

            if (value == Language.GERMAN)
                return "de-DE";

            if (value == Language.ENGLISH_AU)
                return "en-AU";

            if (value == Language.ENGLISH_CA)
                return "en-CA";

            if (value == Language.ENGLISH_UK)
                return "en-GB";

            if (value == Language.ENGLISH_IN)
                return "en-IN";

            if (value == Language.ENGLISH_US)
                return "en-US";

            if (value == Language.ENGLISH_ES)
                return "es-ES";

            if (value == Language.ENGLISH_MX)
                return "es-MX";

            if (value == Language.FINNISH)
                return "fi-FI";

            if (value == Language.FRENCH_CA)
                return "fr-CA";

            if (value == Language.FRENCH_FR)
                return "fr-FR";

            if (value == Language.ITALIAN)
                return "it-IT";

            if (value == Language.JAPANESE)
                return "ja-JP";

            if (value == Language.KOREAN)
                return "ko-KR";

            if (value == Language.NORWEGIAN)
                return "nb-NO";

            if (value == Language.DUTCH)
                return "nl-NL";

            if (value == Language.POLISH)
                return "pl-PL";

            if (value == Language.PORTUGESE_BR)
                return "pt-BR";

            if (value == Language.PORTUGESE_PT)
                return "pt-PT";

            if (value == Language.RUSSIAN)
                return "ru-RU";

            if (value == Language.SWEDISH)
                return "sv-SE";

            if (value == Language.CHINESE_CN)
                return "zh-CN";

            if (value == Language.CHINESE_HK)
                return "zh-HK";

            if (value == Language.CHINESE_TW)
                return "zh-TW";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Language"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class LanguageJsonConverter : JsonConverter<Language>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Language Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Language? result = rawValue == null
                ? null
                : LanguageValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the Language to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="language"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Language language, JsonSerializerOptions options)
        {
            writer.WriteStringValue(language.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Language"/>
    /// </summary>
    public class LanguageNullableJsonConverter : JsonConverter<Language?>
    {
        /// <summary>
        /// Returns a Language from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Language? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Language? result = rawValue == null
                ? null
                : LanguageValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="language"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Language? language, JsonSerializerOptions options)
        {
            writer.WriteStringValue(language?.ToString() ?? "null");
        }
    }

}
