/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = freeclimb.Client.OpenAPIDateConverter;
using freeclimb.Enums;


namespace freeclimb.Enums
{
    /// <summary>
    /// TCR assessment of the brand identification status.
    /// </summary>
    /// <value>TCR assessment of the brand identification status.</value>
    public enum SMSTenDLCBrandIdentityStatus
    {
        /// <summary>
        /// Enum SELF_DECLARED for value: SELF_DECLARED
        /// </summary>
        SELF_DECLARED = 1,

        /// <summary>
        /// Enum UNVERIFIED for value: UNVERIFIED
        /// </summary>
        UNVERIFIED = 2,

        /// <summary>
        /// Enum VERIFIED for value: VERIFIED
        /// </summary>
        VERIFIED = 3,

        /// <summary>
        /// Enum VETTED_VERIFIED for value: VETTED_VERIFIED
        /// </summary>
        VETTED_VERIFIED = 4
    }

    /// <summary>
    /// Converts <see cref="SMSTenDLCBrandIdentityStatus"/> to and from the JSON value
    /// </summary>
    public static class SMSTenDLCBrandIdentityStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SMSTenDLCBrandIdentityStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SMSTenDLCBrandIdentityStatus FromString(string value)
        {
            if (value.Equals("SELF_DECLARED"))
                return SMSTenDLCBrandIdentityStatus.SELF_DECLARED;

            if (value.Equals("UNVERIFIED"))
                return SMSTenDLCBrandIdentityStatus.UNVERIFIED;

            if (value.Equals("VERIFIED"))
                return SMSTenDLCBrandIdentityStatus.VERIFIED;

            if (value.Equals("VETTED_VERIFIED"))
                return SMSTenDLCBrandIdentityStatus.VETTED_VERIFIED;

            throw new NotImplementedException($"Could not convert value to type SMSTenDLCBrandIdentityStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SMSTenDLCBrandIdentityStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SMSTenDLCBrandIdentityStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("SELF_DECLARED"))
                return SMSTenDLCBrandIdentityStatus.SELF_DECLARED;

            if (value.Equals("UNVERIFIED"))
                return SMSTenDLCBrandIdentityStatus.UNVERIFIED;

            if (value.Equals("VERIFIED"))
                return SMSTenDLCBrandIdentityStatus.VERIFIED;

            if (value.Equals("VETTED_VERIFIED"))
                return SMSTenDLCBrandIdentityStatus.VETTED_VERIFIED;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SMSTenDLCBrandIdentityStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SMSTenDLCBrandIdentityStatus value)
        {
            if (value == SMSTenDLCBrandIdentityStatus.SELF_DECLARED)
                return "SELF_DECLARED";

            if (value == SMSTenDLCBrandIdentityStatus.UNVERIFIED)
                return "UNVERIFIED";

            if (value == SMSTenDLCBrandIdentityStatus.VERIFIED)
                return "VERIFIED";

            if (value == SMSTenDLCBrandIdentityStatus.VETTED_VERIFIED)
                return "VETTED_VERIFIED";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SMSTenDLCBrandIdentityStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SMSTenDLCBrandIdentityStatusJsonConverter : JsonConverter<SMSTenDLCBrandIdentityStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SMSTenDLCBrandIdentityStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SMSTenDLCBrandIdentityStatus? result = rawValue == null
                ? null
                : SMSTenDLCBrandIdentityStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SMSTenDLCBrandIdentityStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sMSTenDLCBrandIdentityStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SMSTenDLCBrandIdentityStatus sMSTenDLCBrandIdentityStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(sMSTenDLCBrandIdentityStatus.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SMSTenDLCBrandIdentityStatus"/>
    /// </summary>
    public class SMSTenDLCBrandIdentityStatusNullableJsonConverter : JsonConverter<SMSTenDLCBrandIdentityStatus?>
    {
        /// <summary>
        /// Returns a SMSTenDLCBrandIdentityStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SMSTenDLCBrandIdentityStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SMSTenDLCBrandIdentityStatus? result = rawValue == null
                ? null
                : SMSTenDLCBrandIdentityStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sMSTenDLCBrandIdentityStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SMSTenDLCBrandIdentityStatus? sMSTenDLCBrandIdentityStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(sMSTenDLCBrandIdentityStatus?.ToString() ?? "null");
        }
    }

}
