/*
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = freeclimb.Client.OpenAPIDateConverter;
using freeclimb.Enums;


namespace freeclimb.Enums
{
    /// <summary>
    /// Entity type behind the brand. This is the form of business establishment.
    /// </summary>
    /// <value>Entity type behind the brand. This is the form of business establishment.</value>
    public enum SMSTenDLCBrandEntityType
    {
        /// <summary>
        /// Enum PRIVATE_PROFIT for value: PRIVATE_PROFIT
        /// </summary>
        PRIVATE_PROFIT = 1,

        /// <summary>
        /// Enum PUBLIC_PROFIT for value: PUBLIC_PROFIT
        /// </summary>
        PUBLIC_PROFIT = 2,

        /// <summary>
        /// Enum NON_PROFIT for value: NON_PROFIT
        /// </summary>
        NON_PROFIT = 3,

        /// <summary>
        /// Enum GOVERNMENT for value: GOVERNMENT
        /// </summary>
        GOVERNMENT = 4,

        /// <summary>
        /// Enum SOLE_PROPRIETOR for value: SOLE_PROPRIETOR
        /// </summary>
        SOLE_PROPRIETOR = 5
    }

    /// <summary>
    /// Converts <see cref="SMSTenDLCBrandEntityType"/> to and from the JSON value
    /// </summary>
    public static class SMSTenDLCBrandEntityTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SMSTenDLCBrandEntityType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SMSTenDLCBrandEntityType FromString(string value)
        {
            if (value.Equals("PRIVATE_PROFIT"))
                return SMSTenDLCBrandEntityType.PRIVATE_PROFIT;

            if (value.Equals("PUBLIC_PROFIT"))
                return SMSTenDLCBrandEntityType.PUBLIC_PROFIT;

            if (value.Equals("NON_PROFIT"))
                return SMSTenDLCBrandEntityType.NON_PROFIT;

            if (value.Equals("GOVERNMENT"))
                return SMSTenDLCBrandEntityType.GOVERNMENT;

            if (value.Equals("SOLE_PROPRIETOR"))
                return SMSTenDLCBrandEntityType.SOLE_PROPRIETOR;

            throw new NotImplementedException($"Could not convert value to type SMSTenDLCBrandEntityType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SMSTenDLCBrandEntityType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SMSTenDLCBrandEntityType? FromStringOrDefault(string value)
        {
            if (value.Equals("PRIVATE_PROFIT"))
                return SMSTenDLCBrandEntityType.PRIVATE_PROFIT;

            if (value.Equals("PUBLIC_PROFIT"))
                return SMSTenDLCBrandEntityType.PUBLIC_PROFIT;

            if (value.Equals("NON_PROFIT"))
                return SMSTenDLCBrandEntityType.NON_PROFIT;

            if (value.Equals("GOVERNMENT"))
                return SMSTenDLCBrandEntityType.GOVERNMENT;

            if (value.Equals("SOLE_PROPRIETOR"))
                return SMSTenDLCBrandEntityType.SOLE_PROPRIETOR;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SMSTenDLCBrandEntityType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SMSTenDLCBrandEntityType value)
        {
            if (value == SMSTenDLCBrandEntityType.PRIVATE_PROFIT)
                return "PRIVATE_PROFIT";

            if (value == SMSTenDLCBrandEntityType.PUBLIC_PROFIT)
                return "PUBLIC_PROFIT";

            if (value == SMSTenDLCBrandEntityType.NON_PROFIT)
                return "NON_PROFIT";

            if (value == SMSTenDLCBrandEntityType.GOVERNMENT)
                return "GOVERNMENT";

            if (value == SMSTenDLCBrandEntityType.SOLE_PROPRIETOR)
                return "SOLE_PROPRIETOR";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SMSTenDLCBrandEntityType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SMSTenDLCBrandEntityTypeJsonConverter : JsonConverter<SMSTenDLCBrandEntityType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SMSTenDLCBrandEntityType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SMSTenDLCBrandEntityType? result = rawValue == null
                ? null
                : SMSTenDLCBrandEntityTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SMSTenDLCBrandEntityType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sMSTenDLCBrandEntityType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SMSTenDLCBrandEntityType sMSTenDLCBrandEntityType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(sMSTenDLCBrandEntityType.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SMSTenDLCBrandEntityType"/>
    /// </summary>
    public class SMSTenDLCBrandEntityTypeNullableJsonConverter : JsonConverter<SMSTenDLCBrandEntityType?>
    {
        /// <summary>
        /// Returns a SMSTenDLCBrandEntityType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SMSTenDLCBrandEntityType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SMSTenDLCBrandEntityType? result = rawValue == null
                ? null
                : SMSTenDLCBrandEntityTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sMSTenDLCBrandEntityType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SMSTenDLCBrandEntityType? sMSTenDLCBrandEntityType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(sMSTenDLCBrandEntityType?.ToString() ?? "null");
        }
    }

}
