name: Build & Test .NET Package

on:
  push:
    branches: ["*"]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: stoplight/prism:latest
          run: |
            chmod a+x $(which prism) && prism mock -h 0.0.0.0 https://docs.freeclimb.com/openapi/5db32318158f3e0031167a17
      - name: cURL server
        run: ( curl "http://127.0.0.1:4010/"  )

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
