name: Build & Test .NET Package

on:
  push:
    branches: ["*"]

jobs:
  container-test-job:
    runs-on: ubuntu-latest

    services:
      prismserver:
        image: node:16.14.2-alpine3.15
        ports:
          - 4010:4010
      steps:
        - name: Check for dockerenv file
          run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
        - name: Install Prism
          run: (yarn global add @stoplight/prism-cli)
        - name: Start Prism Server
          run: ( prism mock -h 0.0.0.0 https://docs.freeclimb.com/openapi/5db32318158f3e0031167a17)

    steps:
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: node:16.14.2-alpine3.15
          run: |
            yarn global add @stoplight/prism-cli
            prism mock -h 0.0.0.0 https://docs.freeclimb.com/openapi/5db32318158f3e0031167a17

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: cURL Request to prism server
        run: curl -X GET "http://prismserver:4010/"
      - name: Test
        run: dotnet test --no-restore --verbosity normal
